### ISSUE TITLE
Issue with  unloadable files

### ISSUE THREAD

**Issue by Jintarei** [h3imdall/ftp-remote-edit#10]
Hi,

Your package having some issues on all my computers. When i click on a file for edit this one, lines icons next to the name just turn on himself and doesn't load.

How can i fix it ?

Thanks, best regards

**Comment by h3imdall** [comment]
Hi Jintarei , 

please try it with the latest version. Yesterday i have published a few pataches for version 0.9.0. 
If it does not work. Which operating system do you use and did you try it with ftp or ssh? 

best regards

**Comment by Jintarei** [comment]
Hi,

Since your last update it works better ! So all is ok for me.
Just one thing, the double click on a file don't work correctly, you have to press on the second click to open  the file, how ever it doesn't work

**Comment by h3imdall** [comment]
There is no double click handler in this package. 
To open a file you only need one click.

**Comment by Jintarei** [comment]
Yes you're right, thank you for your responses !
Keep going 👍

**Comment by h3imdall** [comment]
I'm glad i was able to help you.
