### ISSUE TITLE
Can't open multiple files with same path

### ISSUE THREAD

**Issue by kweensey** [h3imdall/ftp-remote-edit#114]
Hi, guys,

I love this package, I use it every single day, awesome work and thanks!

Although, when I want to open multiple files with the same path and filename from multiple FTPs (e.g., _ftp1/web/index.php_ and _ftp2/web/index.php_), it seems like it thinks it is currently opened file and do nothing.

But when paths differ a bit (e.g., _ftp1/web/index.php_ and _ftp2/web/admin/index.php_), it works.

If you could look into this and include fix for this into some of the updates, it would be great.

Have a good one.. :-)

**Comment by cschindl** [comment]
Hi @kweensey,

thank for the hint, I will check that.

**Comment by cschindl** [comment]
Hi @kweensey,

i fixed the error 1fa4b4d11b0444011dad02583788bf9414e063d4. Thank you for your detailed description. Changes are available in the next release.
