### ISSUE TITLE
Support for ECDSA

### ISSUE THREAD

**Issue by amirher** [h3imdall/ftp-remote-edit#118]
Hi,
I have problem connecting SFTP to server which use ECDSA encryption. Error log from server:

Oct 06 16:51:01 hostXX sshd[958]: Received disconnect from XXX.XXX.XXX.XXX: 11:  [preauth]

Is the ftp-remote-edit SSH client support ECDSA?

**Comment by cschindl** [comment]
Hi @amirher,

that a good question. I realy don't know. The package use this library (https://github.com/mscdex/ssh2). Maybe you can find here anything.

**Comment by n8v8R** [comment]
It seems that there is a problem with strong ciphers and also perhaps SSH protocol 3. I cannot connect to the server and the connection icon keeps on spinning endlessly. Those are my sshd settings, which putty cannot handle either, in case this is (would nice to have) package is based on putty 

# Ciphers and keying
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group14-sha256

**Comment by cnrmck** [comment]
@amirher I use ecdsa and it works just fine for me.
