### ISSUE TITLE
Uncaught TypeError: Cannot read property 'collapse' of undefined, and view.open is not a function

### ISSUE THREAD

**Issue by maave0** [h3imdall/ftp-remote-edit#119]
There are a couple slightly-different ways to reproduce. Probably all the same root issue, I just wanted to be thorough.

0. have at least one server in the list

Method 1
1. click on a server nickname
2. hit Left arrow key for "Cannot read property 'collapse' of undefined", or hit Right arrow key for "view.open is not a function"

Method 2
1. expand the directory list on a server
2. click or keyboard nav to highlight any directory
3. use Up arrow key to highlight the server nickname (_not_ the Left button)
4. hit Left or Right arrow keys for errors

Method 3
1. collapse the directories so there's only the server nicknames visible
2. click in the empty area below the server lists
3. hit Left or Right arrow keys for errors

Method 4
1. expand the directory list on a server
2. click or keyboard nav to highlight any directory
3. click in the empty space below the directory list
4. hit Left arrow key to collapse all directories (_not_ the Up button)
5. hit Left or Right arrow keys for errors

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.3

### Stack Trace

Uncaught TypeError: Cannot read property 'collapse' of undefined

```
At C:\Users\robert.hansen\.atom\packages\ftp-remote-edit\lib\views\tree-view.js:480

TypeError: Cannot read property 'collapse' of undefined
    at _TreeView.remoteKeyboardNavigationLeft (/packages/ftp-remote-edit/lib/views/tree-view.js:479:18)
    at _TreeView.remoteKeyboardNavigation (/packages/ftp-remote-edit/lib/views/tree-view.js:418:14)
    at /packages/ftp-remote-edit/lib/views/tree-view.js:152:43)
    at HTMLOListElement.dispatch (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:12.7.0 ftp-remote-edit:toggle (input.hidden-input)
     -0:10.3.0 core:confirm (input.hidden-input)
     -0:05.2.0 core:move-left (ol.ftp-remote-edit-list.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
codeigniter 0.3.2 
ftp-remote-edit 0.12.3 
```

**Comment by cschindl** [comment]
Hi @maave0, 

i fixed the error defe7aec4e3a9121d859fe8f7c9ea0a07040aaca. Thank you for your detailed description. Changes are available in the next release.
