### ISSUE TITLE
Unexpected token v in JSON at position 0

### ISSUE THREAD

**Issue by manuavanca** [h3imdall/ftp-remote-edit#127]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.5

### Stack Trace

Unexpected token v in JSON at position 0

```
At Unexpected token v in JSON at position 0

SyntaxError: Unexpected token v in JSON at position 0
    at JSON.parse (<anonymous>)
    at /packages/ftp-remote-edit/lib/views/tree-view.js:259:29
    at _TreeView.loadServers (/packages/ftp-remote-edit/lib/views/tree-view.js:295:8)
    at /packages/ftp-remote-edit/lib/ftp-remote-edit.js:155:31

Detail: eyJjb25maWciOnsibG9hZCI6dHJ1ZSwiZGVjcnlwdCI6dHJ1ZSwic3RhcnQiOiJ2W  /vVx1MDAxYSIsImVuZCI6Ilx1MDAxN0rspahBIn0sInBhc3N3b3JkIjp7ImV4aXN0cyI6dHJ1ZSwibGVuZ3RoIjoxMSwiYWxwaGFudW1lcmljIjp0cnVlfX0=
```

### Commands

```
     -3:26.7.0 tree-view:toggle-focus (atom-pane.pane.active)
     -3:21.1.0 tree-view:toggle-side (atom-pane.pane.active)
     -2:26.2.0 core:confirm (input.hidden-input)
     -0:13.4.0 ftp-remote-edit:toggle (input#ftp-remote-edit.dev.debug.input-checkbox)
  3x -0:08.8.0 core:backspace (input.hidden-input)
     -0:05.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
ftp-remote-edit 0.12.5 
```

**Comment by cschindl** [comment]
Hi @manuavanca  ,

the error has already been reported in issue #44 and a solution is being worked on.
Could you please enter steps to reproduce and answer the folloing questions:

When does the error occur? (always, sometimes, in special situations...)
Do you use multiple instances of atom at the same time?
Can you reproduce the error?
Did you start with a fresh new installaltion of the plugin?
Can you add new servers?
Do you see the tree view when toggle with ctrl + space?
Did you change the master password?
Do you use non alphanumeric letters in your password?

Please answer in issue #44.
