### ISSUE TITLE
Cannot Delete Server

### ISSUE THREAD

**Issue by Adrian0350** [h3imdall/ftp-remote-edit#129]
I toggled 'Edit Servers > New' by accident and now I cannot remove it from the panel.

**Comment by cschindl** [comment]
Hi @Adrian0350,

in the last update a small error has crept in which caused that changes in the configuration view do not occur immediately after saving. The error has been corrected 73c0e9259d18be4772514fc10ed22389bd822d85  and the changes will be available in the next release.
