### ISSUE TITLE
Unable to enter SSH Key File path.

### ISSUE THREAD

**Issue by calvin3663** [h3imdall/ftp-remote-edit#134]
Package Name: ftp-remote-edit (0.12.6)
OS: Windows 10 Pro

Issue:
There's a small bug within the Edit Server module.
Sometimes, the field to enter SSH Key File path is locked.
Had to close and re-launch ATOM, and open the Edit Server again to able to enter the path.

Should be very easy to fix!

**Comment by cschindl** [comment]
Hi @calvin3663 ,

Can you write me a short step-by-step tutorial so I can reproduce the error?

**Comment by cschindl** [comment]
Please answer here. #75 .
