### ISSUE TITLE
Edit Server or Toggle GUI not working

### ISSUE THREAD

**Issue by dread33** [h3imdall/ftp-remote-edit#135]
When I toggle the package I just see a cursor at the top of the screen and when I try and edit servers I see half of the text for entering a password. I've tried disabling all my Community packages but it still does the same thing. I'm not sure if this is an Atom setting or an issue with the ftp-remote-edit package? Anyone come across this before? Any suggestions?
![image](https://user-images.githubusercontent.com/32363428/32019422-24d3b4b0-b99b-11e7-930f-dd0e160a2f1f.png)

![image](https://user-images.githubusercontent.com/32363428/32019469-5301c516-b99b-11e7-8035-0b0c4464a94e.png)

**Comment by cschindl** [comment]
Hi @dread33,

I think it's a presentation problem caused by the theme. This is what we already had #79
To find the bug I need to know what you are using for a theme.
