### ISSUE TITLE
Copy Local Folder/File Into Remote Server

### ISSUE THREAD

**Issue by grpace** [h3imdall/ftp-remote-edit#138]
It would be great if I can click and drag local directories and files right into the remote server.
It doesn't seem like this is supported right now.

Got excited because I saw:

> Feature request: Drag-and-Drop (issue-25)
> Feature request: Copy / Cut / Paste files (issue-24)

In the v0.12 changelog but doesn't seem like this what I was looking for.

Anyone have any suggestions.

---

If this sort of thing isn't possible a shortcut like "Open In FileZilla" or something would be nice so I don't have to re add my server credentials to copy in some new files to a remote server.

**Comment by cschindl** [comment]
Hi @grpace,
 
The upload of files or folders is currently not supported. At the moment it is only possible to copy/cut/paste/move files/folders in the FTP tree. However, the upload of files should be added. Most of the necessary preparations have already been implemented. Unfortunately, the whole thing is very complicated and time consuming, so it will take some time to implement this feature.

**Comment by luco** [comment]
This would be awesome

**Comment by odil-io** [comment]
Looking very forward to this! So far the plugin behaved fast and as expected.

**Comment by mrcandiess** [comment]
Hi, is there any progress with this feature? If you have already created test branch, I'd like to contribute on this or test it.

This is really necessary feature for me. Thank you!

**Comment by Dave-Skye** [comment]
Hey

Yes this would be the best improvement and make the whole Atom system complete!

Please add this!!!!!

Cheers.

**Comment by jeremiepape** [comment]
+1

**Comment by donsony** [comment]
Must need feature

**Comment by donsony** [comment]
This feature is very much needed. Please add this as priority feature request

**Comment by bartburo3** [comment]
Meanwhile, something has been done with this function? It would really help me if it was in it. @h3imdall @cschindl

**Comment by TomS-** [comment]
I have always used the "remove-ftp" package. However, I found this one was better. One thing being security. I didn't like that FTP/SFTP details were stored as a text file. I also like that you don't need projects. It seems the UI is more considered and it's much cleaner. The only thing that is stopping me making the full switch is this. Being able to download a js file and upload it into the FTP server would be amazing. Whether it's drag and drop doesn't matter to me, but some way of doing it would be amazing.

**Comment by helloromero** [comment]
+1

**Comment by bartburo3** [comment]
@cschindl Hey, is someone developing this now?

**Comment by cschindl** [comment]
I agree with you that this would be a great improvement but the adjustments are very time consuming. Unfortunately, I don't have the time at the moment. So I would be grateful for any help.

**Comment by samazko** [comment]
This would be a great improvement indeed :)

**Comment by wacki4** [comment]
@cschindl - maybe i could help ? ;) If You would only say any approach for this, i think it would be possible for me to write it down

**Comment by cschindl** [comment]
Hi @wacki4,

I'm grateful for any help. I have already made the necessary preparations in the refactoring branch. But now the queue has to be adjusted. 

At the moment there is a global queue for all up- and downloads, but it is only used to show the processes. It would be better, however, if this would also take over the management of the processes, so that new files / directories can be processed in order and failed ones can be retriggered. The abortion of running processes would also have to be ensured. In addition, what should happen to existing directories / files (skip, overwrite)? 

I would have liked to trigger the processing via asynchronous events. Maybe you still have some ideas how to make this easier?

**Comment by cschindl** [comment]
Hi @wacki4, 

You're very welcome to try it. If you need help or suggestions, feel free to contact me. If you start with this, please create a new branch for your fork. Several changes should not be made in the master branch of the forks.

**Comment by wacki4** [comment]
@cschindl - as i see You started download/upload. Do You need help of that with something?

**Comment by cschindl** [comment]
Even if it took a little longer, it is now implemented in release in [0.13.0](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.13.0) ;-)

**Comment by odil-io** [comment]
Awesome! Thank you for your work!
