### ISSUE TITLE
sftp path to private key file greyed

### ISSUE THREAD

**Issue by mickaelmonsieur** [h3imdall/ftp-remote-edit#141]
Hi,
In SFTP, the "path to private key file" is greyed. Why?
Atom 1.21.2 x64 (Mac Os)
FTP remote edit 0.12

**Comment by cschindl** [comment]
Hi @mickaelmonsieur ,

the error has already been reported in issue #75. The error has been corrected 3edc534 and the changes will be available in the next release.
