### ISSUE TITLE
ProtocolItemView.trigger is deprecated.

### ISSUE THREAD

**Issue by nataliescottdavidson** [h3imdall/ftp-remote-edit#142]
Are you trying to dispatch the 'protocol-queue-view:error' Atom command with `jQuery::trigger`?
`jQuery::trigger` can no longer emit Atom commands as it will not correctly route
the command to its handlers. Please use `atom.commands.dispatch` instead.
See the docs at https://atom.io/docs/api/latest/CommandRegistry

**Comment by cschindl** [comment]
Hi @nataliescottdavidson,

the dispatch of errors was modified long time ago in fdc26721d3718c5f36cb526620c43ed5d0aec0eb.  Do you use the latest version of this package 0.12.7?
