### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by gabirosca** [h3imdall/ftp-remote-edit#145]
Installing “ftp-remote-edit@0.12.7” failed.

> coffee-script@1.12.8 postinstall C:\Users\gabir\AppData\Local\Temp\apm-install-dir-1171030-2376-1cqkw5f.uwon8qia4i\node_modules\ftp-remote-edit\node_modules\coffee-script
> node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'

C:\Users\gabir\AppData\Local\Temp\apm-install-dir-1171030-2376-1cqkw5f.uwon8qia4i
`-- (empty)

[eval]:1
'if
^^^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at Immediate.<anonymous> (bootstrap_node.js:357:29)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\gabir\AppData\Local\Temp\apm-install-dir-1171030-2376-1cqkw5f.uwon8qia4i\package.json'
npm WARN apm-install-dir-1171030-2376-1cqkw5f.uwon8qia4i No description
npm WARN apm-install-dir-1171030-2376-1cqkw5f.uwon8qia4i No repository field.
npm WARN apm-install-dir-1171030-2376-1cqkw5f.uwon8qia4i No README data
npm WARN apm-install-dir-1171030-2376-1cqkw5f.uwon8qia4i No license field.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\gabir\\AppData\\Local\\atom\\app-1.22.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\gabir\\AppData\\Local\\atom\\app-1.22.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\gabir\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\gabir\\.atom\\.apmrc" "install" "C:\\Users\\gabir\\AppData\\Local\\Temp\\d-1171030-2376-vl03kh.zjylcsdcxr\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! coffee-script@1.12.8 postinstall: `node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the coffee-script@1.12.8 postinstall script 'node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the coffee-script package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs coffee-script
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls coffee-script
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\gabir\AppData\Local\Temp\apm-install-dir-1171030-2376-1cqkw5f.uwon8qia4i\npm-debug.log
npm ERR! code 1

**Comment by rompeldunk** [comment]
Same https://github.com/h3imdall/ftp-remote-edit/issues/145

Note: Managed to install 0.12.3, but not 0.12.4 through:
` apm install ftp-remote-edit@0.12.3`

**Comment by rompeldunk** [comment]
I retried to `npm install` inside the package/ftp-remote-edit folder, and got the same error as above.
Though now with the extended log-file:
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Vodo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose npm-session 0d1a0d4172f55e9f
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall ftp-remote-edit@0.12.7
7 info lifecycle ftp-remote-edit@0.12.7~preinstall: ftp-remote-edit@0.12.7
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 http fetch GET 304 https://registry.npmjs.org/season 352ms (from cache)
15 silly pacote range manifest for season@^6.0.1 fetched in 394ms
16 http fetch GET 304 https://registry.npmjs.org/cson-parser 34ms (from cache)
17 silly pacote range manifest for cson-parser@^1.3.0 fetched in 38ms
18 http fetch GET 304 https://registry.npmjs.org/coffee-script 38ms (from cache)
19 silly pacote range manifest for coffee-script@^1.10.0 fetched in 40ms
20 silly pacote range manifest for season@^6.0.1 fetched in 3ms
21 silly resolveWithNewModule season@6.0.2 checking installable status
22 silly pacote range manifest for cson-parser@^1.3.0 fetched in 1ms
23 silly resolveWithNewModule cson-parser@1.3.5 checking installable status
24 silly pacote range manifest for coffee-script@^1.10.0 fetched in 1ms
25 silly resolveWithNewModule coffee-script@1.12.8 checking installable status
26 silly currentTree ftp-remote-edit@0.12.7
26 silly currentTree +-- @icetee/ftp@0.3.11
26 silly currentTree +-- ansi-regex@2.1.1
26 silly currentTree +-- asn1@0.2.3
26 silly currentTree +-- async@1.5.2
26 silly currentTree +-- atom-select-list@0.3.2
26 silly currentTree +-- atom-space-pen-views@2.2.0
26 silly currentTree +-- balanced-match@1.0.0
26 silly currentTree +-- brace-expansion@1.1.8
26 silly currentTree +-- camelcase@2.1.1
26 silly currentTree +-- charenc@0.0.2
26 silly currentTree +-- cliui@3.2.0
26 silly currentTree +-- code-point-at@1.1.0
26 silly currentTree +-- concat-map@0.0.1
26 silly currentTree +-- core-util-is@1.0.2
26 silly currentTree +-- crypt@0.0.2
26 silly currentTree +-- d@0.1.1
26 silly currentTree +-- decamelize@1.2.0
26 silly currentTree +-- emissary@1.3.3
26 silly currentTree +-- es5-ext@0.10.37
26 silly currentTree | +-- d@1.0.0
26 silly currentTree | +-- es6-iterator@2.0.3
26 silly currentTree | `-- es6-symbol@3.1.1
26 silly currentTree +-- es6-iterator@0.1.3
26 silly currentTree +-- es6-symbol@2.0.1
26 silly currentTree +-- es6-weak-map@0.1.4
26 silly currentTree +-- etch@0.12.7
26 silly currentTree +-- fs-plus@3.0.1
26 silly currentTree +-- fs.realpath@1.0.0
26 silly currentTree +-- ftp@0.3.10
26 silly currentTree +-- fuzzaldrin-plus@0.5.0
26 silly currentTree +-- fuzzaldrin@2.1.0
26 silly currentTree +-- glob@7.1.2
26 silly currentTree | `-- minimatch@3.0.4
26 silly currentTree +-- grim@1.5.0
26 silly currentTree +-- hash-string@1.0.0
26 silly currentTree +-- inflight@1.0.6
26 silly currentTree +-- inherits@2.0.3
26 silly currentTree +-- invert-kv@1.0.0
26 silly currentTree +-- is-buffer@1.1.6
26 silly currentTree +-- is-fullwidth-code-point@1.0.0
26 silly currentTree +-- isarray@0.0.1
26 silly currentTree +-- jquery@2.1.4
26 silly currentTree +-- key-path-helpers@0.4.0
26 silly currentTree +-- lcid@1.0.0
26 silly currentTree +-- lru-cache@2.7.3
26 silly currentTree +-- md5@2.2.1
26 silly currentTree +-- minimatch@3.0.4
26 silly currentTree +-- minimist@0.0.8
26 silly currentTree +-- mixto@1.0.0
26 silly currentTree +-- mkdirp@0.5.1
26 silly currentTree +-- number-is-nan@1.0.1
26 silly currentTree +-- once@1.4.0
26 silly currentTree +-- os-locale@1.4.0
26 silly currentTree +-- path-is-absolute@1.0.1
26 silly currentTree +-- property-accessors@1.1.3
26 silly currentTree +-- readable-stream@1.1.14
26 silly currentTree +-- rimraf@2.6.2
26 silly currentTree +-- short-hash@1.0.0
26 silly currentTree +-- sigmund@1.0.1
26 silly currentTree +-- space-pen@5.1.2
26 silly currentTree +-- ssh2-sftp-client@1.1.0
26 silly currentTree +-- ssh2-streams@0.0.23
26 silly currentTree | `-- readable-stream@1.0.34
26 silly currentTree +-- ssh2@0.4.15
26 silly currentTree | `-- readable-stream@1.0.34
26 silly currentTree +-- streamsearch@0.1.2
26 silly currentTree +-- string_decoder@0.10.31
26 silly currentTree +-- string-width@1.0.2
26 silly currentTree +-- strip-ansi@3.0.1
26 silly currentTree +-- underscore-plus@1.6.6
26 silly currentTree +-- underscore@1.6.0
26 silly currentTree +-- window-size@0.1.4
26 silly currentTree +-- wrap-ansi@2.1.0
26 silly currentTree +-- wrappy@1.0.2
26 silly currentTree +-- xregexp@2.0.0
26 silly currentTree +-- y18n@3.2.1
26 silly currentTree `-- yargs@3.32.0
27 silly idealTree ftp-remote-edit@0.12.7
27 silly idealTree +-- @icetee/ftp@0.3.11
27 silly idealTree +-- ansi-regex@2.1.1
27 silly idealTree +-- asn1@0.2.3
27 silly idealTree +-- async@1.5.2
27 silly idealTree +-- atom-select-list@0.3.2
27 silly idealTree +-- atom-space-pen-views@2.2.0
27 silly idealTree +-- balanced-match@1.0.0
27 silly idealTree +-- brace-expansion@1.1.8
27 silly idealTree +-- camelcase@2.1.1
27 silly idealTree +-- charenc@0.0.2
27 silly idealTree +-- cliui@3.2.0
27 silly idealTree +-- code-point-at@1.1.0
27 silly idealTree +-- coffee-script@1.12.8
27 silly idealTree +-- concat-map@0.0.1
27 silly idealTree +-- core-util-is@1.0.2
27 silly idealTree +-- crypt@0.0.2
27 silly idealTree +-- cson-parser@1.3.5
27 silly idealTree +-- d@0.1.1
27 silly idealTree +-- decamelize@1.2.0
27 silly idealTree +-- emissary@1.3.3
27 silly idealTree +-- es5-ext@0.10.37
27 silly idealTree | +-- d@1.0.0
27 silly idealTree | +-- es6-iterator@2.0.3
27 silly idealTree | `-- es6-symbol@3.1.1
27 silly idealTree +-- es6-iterator@0.1.3
27 silly idealTree +-- es6-symbol@2.0.1
27 silly idealTree +-- es6-weak-map@0.1.4
27 silly idealTree +-- etch@0.12.7
27 silly idealTree +-- fs-plus@3.0.1
27 silly idealTree +-- fs.realpath@1.0.0
27 silly idealTree +-- fuzzaldrin-plus@0.5.0
27 silly idealTree +-- fuzzaldrin@2.1.0
27 silly idealTree +-- glob@7.1.2
27 silly idealTree | `-- minimatch@3.0.4
27 silly idealTree +-- grim@1.5.0
27 silly idealTree +-- hash-string@1.0.0
27 silly idealTree +-- inflight@1.0.6
27 silly idealTree +-- inherits@2.0.3
27 silly idealTree +-- invert-kv@1.0.0
27 silly idealTree +-- is-buffer@1.1.6
27 silly idealTree +-- is-fullwidth-code-point@1.0.0
27 silly idealTree +-- isarray@0.0.1
27 silly idealTree +-- jquery@2.1.4
27 silly idealTree +-- key-path-helpers@0.4.0
27 silly idealTree +-- lcid@1.0.0
27 silly idealTree +-- md5@2.2.1
27 silly idealTree +-- minimatch@3.0.4
27 silly idealTree +-- minimist@0.0.8
27 silly idealTree +-- mixto@1.0.0
27 silly idealTree +-- mkdirp@0.5.1
27 silly idealTree +-- number-is-nan@1.0.1
27 silly idealTree +-- once@1.4.0
27 silly idealTree +-- os-locale@1.4.0
27 silly idealTree +-- path-is-absolute@1.0.1
27 silly idealTree +-- property-accessors@1.1.3
27 silly idealTree +-- readable-stream@1.1.14
27 silly idealTree +-- rimraf@2.6.2
27 silly idealTree +-- season@6.0.2
27 silly idealTree +-- short-hash@1.0.0
27 silly idealTree +-- space-pen@5.1.2
27 silly idealTree +-- ssh2-streams@0.0.23
27 silly idealTree | `-- readable-stream@1.0.34
27 silly idealTree +-- ssh2@0.4.15
27 silly idealTree | `-- readable-stream@1.0.34
27 silly idealTree +-- streamsearch@0.1.2
27 silly idealTree +-- string_decoder@0.10.31
27 silly idealTree +-- string-width@1.0.2
27 silly idealTree +-- strip-ansi@3.0.1
27 silly idealTree +-- underscore-plus@1.6.6
27 silly idealTree +-- underscore@1.6.0
27 silly idealTree +-- window-size@0.1.4
27 silly idealTree +-- wrap-ansi@2.1.0
27 silly idealTree +-- wrappy@1.0.2
27 silly idealTree +-- xregexp@2.0.0
27 silly idealTree +-- y18n@3.2.1
27 silly idealTree `-- yargs@3.32.0
28 silly install generateActionsToTake
29 silly diffTrees action count 7
30 silly diffTrees add coffee-script@1.12.8
31 silly diffTrees add cson-parser@1.3.5
32 silly diffTrees remove ftp@0.3.10
33 silly diffTrees remove lru-cache@2.7.3
34 silly diffTrees add season@6.0.2
35 silly diffTrees remove sigmund@1.0.1
36 silly diffTrees remove ssh2-sftp-client@1.1.0
37 silly decomposeActions action count 32
38 silly decomposeActions fetch coffee-script@1.12.8
39 silly decomposeActions extract coffee-script@1.12.8
40 silly decomposeActions preinstall coffee-script@1.12.8
41 silly decomposeActions build coffee-script@1.12.8
42 silly decomposeActions install coffee-script@1.12.8
43 silly decomposeActions postinstall coffee-script@1.12.8
44 silly decomposeActions finalize coffee-script@1.12.8
45 silly decomposeActions refresh-package-json coffee-script@1.12.8
46 silly decomposeActions fetch cson-parser@1.3.5
47 silly decomposeActions extract cson-parser@1.3.5
48 silly decomposeActions preinstall cson-parser@1.3.5
49 silly decomposeActions build cson-parser@1.3.5
50 silly decomposeActions install cson-parser@1.3.5
51 silly decomposeActions postinstall cson-parser@1.3.5
52 silly decomposeActions finalize cson-parser@1.3.5
53 silly decomposeActions refresh-package-json cson-parser@1.3.5
54 silly decomposeActions unbuild ftp@0.3.10
55 silly decomposeActions remove ftp@0.3.10
56 silly decomposeActions unbuild lru-cache@2.7.3
57 silly decomposeActions remove lru-cache@2.7.3
58 silly decomposeActions fetch season@6.0.2
59 silly decomposeActions extract season@6.0.2
60 silly decomposeActions preinstall season@6.0.2
61 silly decomposeActions build season@6.0.2
62 silly decomposeActions install season@6.0.2
63 silly decomposeActions postinstall season@6.0.2
64 silly decomposeActions finalize season@6.0.2
65 silly decomposeActions refresh-package-json season@6.0.2
66 silly decomposeActions unbuild sigmund@1.0.1
67 silly decomposeActions remove sigmund@1.0.1
68 silly decomposeActions unbuild ssh2-sftp-client@1.1.0
69 silly decomposeActions remove ssh2-sftp-client@1.1.0
70 silly install executeActions
71 silly doSerial global-install 32
72 verbose correctMkdir C:\Users\Vodo\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
73 verbose lock using C:\Users\Vodo\AppData\Roaming\npm-cache\_locks\staging-c79b2604763878f7.lock for C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\.staging
74 silly doParallel extract 32
75 silly extract coffee-script@1.12.8
76 silly pacote trying coffee-script@https://registry.npmjs.org/coffee-script/-/coffee-script-1.12.8.tgz by hash: sha512-VMFKJK+3Ddjs7e/wXfLV+7oxEp1RS7u8W0Xja26Ky5Me8F1mulvhUGFXTL9qdPId30ID3dwEkDC8eGwAr3oL+w==
77 silly extract cson-parser@1.3.5
78 silly pacote trying cson-parser@https://registry.npmjs.org/cson-parser/-/cson-parser-1.3.5.tgz by hash: sha1-fsZ14DkUVTO/KmqFYHPxWZ2cLSQ=
79 silly extract season@6.0.2
80 silly pacote trying season@https://registry.npmjs.org/season/-/season-6.0.2.tgz by hash: sha1-naWPsd3SSCTXYhstxjpxI7UCF7Y=
81 silly pacote season@https://registry.npmjs.org/season/-/season-6.0.2.tgz extracted to C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\.staging\season-42933f5d by content address 87ms
82 silly pacote cson-parser@https://registry.npmjs.org/cson-parser/-/cson-parser-1.3.5.tgz extracted to C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\.staging\cson-parser-77f3c655 by content address 90ms
83 silly pacote coffee-script@https://registry.npmjs.org/coffee-script/-/coffee-script-1.12.8.tgz extracted to C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\.staging\coffee-script-ab7edfd0 by content address 141ms
84 silly doReverseSerial unbuild 32
85 silly unbuild ssh2-sftp-client@1.1.0
86 info lifecycle ssh2-sftp-client@1.1.0~preuninstall: ssh2-sftp-client@1.1.0
87 info lifecycle ssh2-sftp-client@1.1.0~uninstall: ssh2-sftp-client@1.1.0
88 verbose unbuild rmStuff ssh2-sftp-client@1.1.0 from C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules
89 info lifecycle ssh2-sftp-client@1.1.0~postuninstall: ssh2-sftp-client@1.1.0
90 silly unbuild sigmund@1.0.1
91 info lifecycle sigmund@1.0.1~preuninstall: sigmund@1.0.1
92 info lifecycle sigmund@1.0.1~uninstall: sigmund@1.0.1
93 verbose unbuild rmStuff sigmund@1.0.1 from C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules
94 info lifecycle sigmund@1.0.1~postuninstall: sigmund@1.0.1
95 silly unbuild lru-cache@2.7.3
96 info lifecycle lru-cache@2.7.3~preuninstall: lru-cache@2.7.3
97 info lifecycle lru-cache@2.7.3~uninstall: lru-cache@2.7.3
98 verbose unbuild rmStuff lru-cache@2.7.3 from C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules
99 info lifecycle lru-cache@2.7.3~postuninstall: lru-cache@2.7.3
100 silly unbuild ftp@0.3.10
101 info lifecycle ftp@0.3.10~preuninstall: ftp@0.3.10
102 info lifecycle ftp@0.3.10~uninstall: ftp@0.3.10
103 verbose unbuild rmStuff ftp@0.3.10 from C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules
104 info lifecycle ftp@0.3.10~postuninstall: ftp@0.3.10
105 silly doSerial remove 32
106 silly remove C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\ftp
107 silly remove C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\lru-cache
108 silly remove C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\sigmund
109 silly remove C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\ssh2-sftp-client
110 silly doSerial move 32
111 silly doSerial finalize 32
112 silly finalize C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\coffee-script
113 silly finalize C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\cson-parser
114 silly finalize C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\season
115 silly doParallel refresh-package-json 32
116 silly refresh-package-json C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\coffee-script
117 silly refresh-package-json C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\cson-parser
118 silly refresh-package-json C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\season
119 silly doParallel preinstall 32
120 silly preinstall coffee-script@1.12.8
121 info lifecycle coffee-script@1.12.8~preinstall: coffee-script@1.12.8
122 silly preinstall cson-parser@1.3.5
123 info lifecycle cson-parser@1.3.5~preinstall: cson-parser@1.3.5
124 silly preinstall season@6.0.2
125 info lifecycle season@6.0.2~preinstall: season@6.0.2
126 silly doSerial build 32
127 silly build coffee-script@1.12.8
128 info linkStuff coffee-script@1.12.8
129 silly linkStuff coffee-script@1.12.8 has C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules as its parent node_modules
130 verbose linkBins coffee-script@1.12.8
131 verbose linkBins [ { coffee: './bin/coffee', cake: './bin/cake' },
131 verbose linkBins   'C:\\Users\\Vodo\\.atom\\packages\\ftp-remote-edit\\node_modules\\.bin',
131 verbose linkBins   false ]
132 verbose linkMans coffee-script@1.12.8
133 silly build cson-parser@1.3.5
134 info linkStuff cson-parser@1.3.5
135 silly linkStuff cson-parser@1.3.5 has C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules as its parent node_modules
136 verbose linkBins cson-parser@1.3.5
137 verbose linkMans cson-parser@1.3.5
138 silly build season@6.0.2
139 info linkStuff season@6.0.2
140 silly linkStuff season@6.0.2 has C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules as its parent node_modules
141 verbose linkBins season@6.0.2
142 verbose linkBins [ { csonc: './bin/csonc' },
142 verbose linkBins   'C:\\Users\\Vodo\\.atom\\packages\\ftp-remote-edit\\node_modules\\.bin',
142 verbose linkBins   false ]
143 verbose linkMans season@6.0.2
144 silly doSerial global-link 32
145 silly doParallel update-linked 32
146 silly doSerial install 32
147 silly install coffee-script@1.12.8
148 info lifecycle coffee-script@1.12.8~install: coffee-script@1.12.8
149 silly install cson-parser@1.3.5
150 info lifecycle cson-parser@1.3.5~install: cson-parser@1.3.5
151 silly install season@6.0.2
152 info lifecycle season@6.0.2~install: season@6.0.2
153 silly doSerial postinstall 32
154 silly postinstall coffee-script@1.12.8
155 info lifecycle coffee-script@1.12.8~postinstall: coffee-script@1.12.8
156 verbose lifecycle coffee-script@1.12.8~postinstall: unsafe-perm in lifecycle true
157 verbose lifecycle coffee-script@1.12.8~postinstall: PATH: C:\Users\Vodo\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\coffee-script\node_modules\.bin;C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\Skype\Phone;C:\Program Files (x86)\Microsoft SQL Server\80\Tools\Binn;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Common Files\AspenTech Shared;C:\Program Files\MATLAB\R2014a\runtime\win64;C:\Program Files\MATLAB\R2014a\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Dell\SysMgt\shared\bin;C:\Users\Vodo\AppData\Local\Android\sdk2\platform-tools;C:\Program Files\OpenVPN\bin;C:\WINDOWS\System32\Windows System Resource Manager\bin;C:\WINDOWS\idmu\common;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Vodo\Anaconda3;C:\Users\Vodo\Anaconda3\Scripts;C:\Users\Vodo\Anaconda3\Library\bin;C:\Users\Vodo\AppData\Local\Microsoft\WindowsApps;C:\Users\Vodo\AppData\Local\atom\bin;C:\Users\Vodo\AppData\Roaming\npm
158 verbose lifecycle coffee-script@1.12.8~postinstall: CWD: C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\coffee-script
159 silly lifecycle coffee-script@1.12.8~postinstall: Args: [ '/d /s /c',
159 silly lifecycle   'node --eval \'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\\x1b[31m"; yellow = "\\x1b[33m"; cyan = "\\x1b[36m"; reset = "\\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\\"coffee-script\\"" + reset + " to use " + yellow + "\\"coffeescript\\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }\'' ]
160 silly lifecycle coffee-script@1.12.8~postinstall: Returned: code: 1  signal: null
161 info lifecycle coffee-script@1.12.8~postinstall: Failed to exec postinstall script
162 verbose unlock done using C:\Users\Vodo\AppData\Roaming\npm-cache\_locks\staging-c79b2604763878f7.lock for C:\Users\Vodo\.atom\packages\ftp-remote-edit\node_modules\.staging
163 verbose stack Error: coffee-script@1.12.8 postinstall: `node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'`
163 verbose stack Exit status 1
163 verbose stack     at EventEmitter.<anonymous> (C:\Users\Vodo\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
163 verbose stack     at emitTwo (events.js:126:13)
163 verbose stack     at EventEmitter.emit (events.js:214:7)
163 verbose stack     at ChildProcess.<anonymous> (C:\Users\Vodo\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
163 verbose stack     at emitTwo (events.js:126:13)
163 verbose stack     at ChildProcess.emit (events.js:214:7)
163 verbose stack     at maybeClose (internal/child_process.js:925:16)
163 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
164 verbose pkgid coffee-script@1.12.8
165 verbose cwd C:\Users\Vodo\.atom\packages\ftp-remote-edit
166 verbose Windows_NT 10.0.15063
167 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Vodo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
168 verbose node v8.9.1
169 verbose npm  v5.5.1
170 error code ELIFECYCLE
171 error errno 1
172 error coffee-script@1.12.8 postinstall: `node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'`
172 error Exit status 1
173 error Failed at the coffee-script@1.12.8 postinstall script.
173 error This is probably not a problem with npm. There is likely additional logging output above.
174 verbose exit [ 1, true ]
`

**Comment by cschindl** [comment]
Hi @gabirosca, @rompeldunk,

atom uses its own nodejs version. Therefore, you should only use "apm install" and never "npm install". Have you tried to install the current version with "apm install ftp-remote-edit@0.12.7" or via the user interface of Atom?

**Comment by rompeldunk** [comment]
Hi @cschindl 
yes, I know. I've tried the following: 
`apm install ftp-remote-edit@0.12.0->0.12.7`
As mentioned, 0.12.3 is the last version I can install. 0.12.4 -> 0.12.7 failed.

**Solution:** Update: I just uninstalled node.js+npm package (v.8.9.1 or v9.0.2) I've installed  to force the package to use the included npm installer instead, and I managed to install 0.12.7 just now :)

@cschindl : Just before the uninstall of NPM+Node.js (v8.9.1) I tried the above command. I got a new errormessage:
`
PS C:\Users\Vodo> apm install ftp-remote-edit@0.12.7
Installing ftp-remote-edit@0.12.7 to C:\Users\Vodo\.atom\packages failed
undefined`

Have you made any updates?

**Comment by cschindl** [comment]
Hi @rompeldunk, 

I haven't made any changes. I think your nodejs installation was faulty. I have installed nodejs globally myself and no problems with the apm installer. It's a good thing that you have now successfully installed the latest version. I'm closing the ticket now.

**Comment by rompeldunk** [comment]
All good. Yes, it was a global problem. Without Node.js/npm core installed it went flawlessly.
