### ISSUE TITLE
Download to local project

### ISSUE THREAD

**Issue by rmagnuson** [h3imdall/ftp-remote-edit#146]
This probably goes against the whole concept of remote editing, but I'd like to actually be able to download particular files, perhaps by right-click menu or by having the option for it to occur automatically when opening a remote file. The reason for this being that I use GIT on my project folders and want to be able to save diff changes as I make edits.

**Comment by cschindl** [comment]
Hi @rmagnuson, 

your wish has already been suggested in #50. Since the files are stored in a temporary directory and do not end up in the current project, I don't think this function is integrable.
