### ISSUE TITLE
Don't allow multiple editor instances of the same remote file

### ISSUE THREAD

**Issue by bogo666** [h3imdall/ftp-remote-edit#149]
It wasn't obvious to me that by clicking on the same remote file that Atom would not be editing the same local buffer version.

Unfortunately I lost a days worth of work by saving new mods in the other version, with no way to recover :-(

**Comment by cschindl** [comment]
Hi @bogo666,

Your wish has already been reported in #99. Unfortunately we have no influence on the behaviour of atom, we can only include a check of the remote files when saving, which checks if they have been changed in the meantime by someone else.
