### ISSUE TITLE
"Permission denied" error when trying to create new folder

### ISSUE THREAD

**Issue by jordan-webdev** [h3imdall/ftp-remote-edit#151]
I am unable to upload a new folder to my server. I am having this issue on two different servers. What do I need to do in order to assist with resolving this issue? Is there a log, or something, I can copy that will help?

**Comment by cschindl** [comment]
Hello @jordan-webdev, 

I apologize for the late answer. To help you with your problem, I need some information:

1. Do you use FTP or SFTP to connect to the server?
2. Have you checked the access rights on the server and maybe you tried to reconstruct the situation with another FTP program like Filezilla?
3. Have you activated the developer mode and can you send me the output from the console? (see https://github.com/h3imdall/ftp-remote-edit#package-preferences)

**Comment by jordan-webdev** [comment]
1. SFTP
2. It works in FileZilla
3. I turned on developer mode...but the console just tells me previous files that either finished or had an error. It gives no information about the new folder I'm trying to create. Is there some other log I should be accessing? For example, here are the top three messages:

path/to/my/file --> path/to/remote/file 604 604(100.0%) Finished
path/to/my/file --> path/to/remote/file 604 604(100.0%) Error
path/to/my/file --> path/to/remote/file 604 230(100.0%) Finished

I opened the console in developer tools, but don't see any messages outputting there. The only message is a CSS error from the perfectionist package

**Comment by cschindl** [comment]
Hello @jordan-webdev ,

this is my fault. I had overlooked that you tried to create a folder and not upload a file. There is no log for creating folders. Only the up- and download of files and server generated error messages are logged. If the developer console does not issue a Javascript error and the server does not send an error message, there is unfortunately no way for you to send me a log. I think you're missing permissions on the server. You could just give me the credentials for the server, so I can reconstruct it.

**Comment by jordan-webdev** [comment]
Hmm, not so sure my boss would be OK with that...any chance you could let me know what I could tell my hosting provider so that they may do it instead? Thanks for your time : ).

**Comment by cschindl** [comment]
Hi @jordan-webdev 

your hosting provider will not be able to fix the problem if they don't know the reason.  The error will be in the SFTP library or in the plugin itself. If you can't provide me with any credentials for testing, you will probably have to find the bug yourself. 

I'd start the search here:
https://github.com/h3imdall/ftp-remote-edit/blob/184e16c6dd4d51ad67a093e6fb602bf787faca06/lib/connectors/sftp.js#L138

**Comment by jordan-webdev** [comment]
Hey I know this is closed, but I'm confused on how there would bean error in the SFTP library or plugin itself. I have not made any changes to the files, so what I'm using should be the same as everyone else. How could there be any error?
