### ISSUE TITLE
Initial Configuration

### ISSUE THREAD

**Issue by munty2k** [h3imdall/ftp-remote-edit#153]
I am trying to configure this on my mac but when I perform the ctrl-space, all I can see is a tiny little box across the top of the Atom screen with no options to confirm the password.

When clicking edit servers from the packages menu, again all I can see is a tiny window across the top as per my attached screenshot.

Any ideas on what I am doing wrong?

thanks
![screen shot 2018-01-08 at 09 26 08](https://user-images.githubusercontent.com/35218763/34664897-fee58e04-f455-11e7-805d-fcd11bf522ca.png)

**Comment by cschindl** [comment]
Hi @munty2k ,

the issue has already been reported in #79. The error is in the used theme. Use a different theme or follow the entries in the issue.

**Comment by munty2k** [comment]
Thank you for such a prompt response. I had searched around in previous
issues but I hadn't been able to find one.

Once again thank you for your assistance and changing the theme worked
straight away.

Kind regards

Munty
