### ISSUE TITLE
MacOS Temp

### ISSUE THREAD

**Issue by mumbaicat** [h3imdall/ftp-remote-edit#154]
Hello, my server file is lost. I want to try to find out which files from my native cache and where to cache the directory in MacOS. Thanks

**Comment by cschindl** [comment]
Hi @mumbaicat,
 
The files are stored in the temporary directory of the OS according to the following scheme:
temp-directory / hash of server / name of the server
e. g. for Windows. C:\Users\CSCHINDL\AppData\Local\Temp\576a7045\localhost.local\.bashrc

Unfortunately I can't tell you exactly where the temp directory is located in MacOS.
The easiest way is to open a file (that can be overwritten locally) via FTP-Remote-Edit on the server. This will download it to the temp. directory and you can view the path.
