### ISSUE TITLE
Encoding when saving file to remote always utf-8

### ISSUE THREAD

**Issue by thomaswasle** [h3imdall/ftp-remote-edit#155]
The encoding when saving a file to remote ist always set to utf-8. Even if the file has another encoding. I tested with iso 8859-1. For connecting to remote I use sftp.

**Comment by cschindl** [comment]
Hi @thomaswasle,

I was able to reproduce the error. Changes are included in the next release.

**Comment by cschindl** [comment]
Fixed in [v0.12.8](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.12.8)
