### ISSUE TITLE
FTP Server File Location

### ISSUE THREAD

**Issue by budzo** [h3imdall/ftp-remote-edit#156]
I want to add multiple FTP server connection locations at one time (over 300) without going through the "Edit Servers" dialog. Is there a file that stores all the servers that can be edited?

**Comment by cschindl** [comment]
Hello @budzo 

the settings are stored encrypted in the atom settings in the file config.cson. Unfortunately, there is no mass import. You could create a file with the following schema and encrypt it by aes-256-ctr with your master password. Then you can enter the encrypted text into the config. cson file.

{
  "name": "new serve 1r",
  "host": "",
  "port": "",
  "user": "",
  "password": "",
  "sftp": false,
  "privatekeyfile": "",
  "remote": "/"
},
{
  "name": "new server 2",
  "host": "",
  "port": "",
  "user": "",
  "password": "",
  "sftp": false,
  "privatekeyfile": "",
  "remote": "/"
}

**Comment by cschindl** [comment]
Maybe you could also help me to implement the import function of Filezila files (issue-#49)?
