### ISSUE TITLE
Auto Reveal Active file in Tree 

### ISSUE THREAD

**Issue by mujuk10dan** [h3imdall/ftp-remote-edit#158]
Is this feature in ftp-remote-edit?

![b053545f4987616a](https://user-images.githubusercontent.com/3067921/35364702-7d12b26a-0168-11e8-8f9b-597ca748f422.gif)

or any other suggestions?

**Comment by cschindl** [comment]
Hi @mujuk10dan,

No, this function is currently not available. The function sounds very interesting. I'll take it as a feature request.
