### ISSUE TITLE
Git highlighting in tree view

### ISSUE THREAD

**Issue by MaximeBouton** [h3imdall/ftp-remote-edit#166]
Hello, 
The git highlighting is disabled in the FTP tree view. Is there a way to turn it on?
I would really appreciate this feature, in the default atom tree view it toggles when a .git folder is present in the project folder. 
Thanks

**Comment by cschindl** [comment]
Hi @MaximeBouton,

your wish has already been suggested in #71. I think this is technically not possible because GIT only works on the local file system. Correct me if I am wrong but I know no way over FTP the GIT status of files to determine.
