### ISSUE TITLE
Feature: Multiple users edit same file

### ISSUE THREAD

**Issue by Eirikvv** [h3imdall/ftp-remote-edit#167]
This would be great for the group projects that i do. It would also save time when there are multiple people ready to work on different functions within the same "page", i know the files could be split up, but in school projects this would help cut time.

example: Teletype + ftp-remote-edit

**Comment by cschindl** [comment]
Hi @Eirikvv,

working on one and the same file at the same time via ftp/sftp doesn't seem to me to make sense. I would recommend you take a closer look at GIT. It's an excellent version control system that allows you to work in parallel without overwriting each other.
