### ISSUE TITLE
Feature: toggle on atom startup

### ISSUE THREAD

**Issue by mostafaasadi** [h3imdall/ftp-remote-edit#168]
Hi
thank you for nice and usefull package :rose: 
may we have a  toggle and connect on startup option ? that toggle ftp dock and connect to server on atom startup automatically

**Comment by mostafaasadi** [comment]
for now we have these steps : 
1. alt+space to toggle
2. type password to open and connect

I think we can improve it with bypass step 1
also I think for someone who is sure about his system security and physical access , we can bypass step 2 , it means server details are saved with encryption on disk but at atom startup will access them unsecure
**although I am not sure about second offer**

**Comment by cschindl** [comment]
Hi @mostafaasadi,

by bypassing step 1, I can live with the fact that this can be done automatically with an additional entry in the settings on program startup. However, step 2 must remain for security reasons.

I'll allow "toggle on startup" option as a feauture request.
