### ISSUE TITLE
Styles for light theme

### ISSUE THREAD

**Issue by TakahashiEi** [h3imdall/ftp-remote-edit#17]
I use light theme. So I cannot read focused folder/file name in remote tree because its fore color is black and background color is black too.
It would be great if you could adjust styles for light theme.

**Comment by h3imdall** [comment]
Thank you for your notification.
I have published a new version. Now you can use the light theme. :)

**Comment by TakahashiEi** [comment]
Rapid and perfect work!
Thank you.
