### ISSUE TITLE
Feature Add - Upload any File in the Filesystem

### ISSUE THREAD

**Issue by triplesam** [h3imdall/ftp-remote-edit#170]
It will be a nice feature to select a file in the Project section and copy it and it is possible to insert it in the Ftp-Remote-Edit Pane.

**Comment by cschindl** [comment]
Hi @triplesam,

your wish has already been suggested in #138. Most of the necessary preparations have already been implemented. Unfortunately, the whole thing is very complicated and time consuming. I don't have the time to make the necessary adjustments at the moment. Maybe you could help us?
