### ISSUE TITLE
Option for double-click on treeview

### ISSUE THREAD

**Issue by rgnyldz** [h3imdall/ftp-remote-edit#171]
It would be nice to have an option to chose between double-click and single-click on treeview.

Sometimes we need to click a folder and find the right file by clicking a letter.

**Comment by cschindl** [comment]
Hi @rgnyldz,

like the atom editor, the package uses the "Allow Pending Pane Items" option. This allow items to be previewed without adding them to a pane permanently by open it with a single click. Files which  opened with a double click are added permanently. If you deactivate this option, all files will only be opened by double-clicking on them.

**Comment by FabrizioCaldarelli** [comment]
On Mac 10.13.3, also checking "Allow Pending Pane Items", the first click on treeview open the editor pane.

**Comment by FabrizioCaldarelli** [comment]
It should be solved with PR: https://github.com/h3imdall/ftp-remote-edit/pull/177

**Comment by cschindl** [comment]
The feature has been added 97e03b7dde719157a90fbb916fe31fc5464e49de and the changes will be available in the next release.
