### ISSUE TITLE
Unable to open after upgrade to 0.12.10

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [h3imdall/ftp-remote-edit#172]
After upgrading to 0.12.10, Atom is unable to open ftp-remote-edit, usign ALT+Space (on Mac) or clicking on Toggle on Ftp-Remote from Packages menu.

I've tried to make a clear installation of Atom and installing again Ftp-Remote, but it does not start.

In developer console I see no errors.

**Comment by cschindl** [comment]
Hi @FabrizioCaldarelli,

thanks for the tip. The error has been fixed. Please update to version 0.12.11

**Comment by FabrizioCaldarelli** [comment]
Thank you very much. Your package is awesome!
