### ISSUE TITLE
editor.getPath does not accept parameter

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [h3imdall/ftp-remote-edit#175]
Why are you passing "false" parameter to editor.getPath() ?

https://github.com/h3imdall/ftp-remote-edit/blob/8434059e0fd482703ef61fdda8567e6a2991fd1c/lib/ftp-remote-edit.js#L582

This could be related to #173 issue

**Comment by cschindl** [comment]
Hi @FabrizioCaldarelli,

thanks for the tip and your contribution. That's a mistake, of course. In the FileView, DirectoryView I use the function with the same name but with parameters.  The parameter can therefore be removed. However, it is more important to check if the function returns a path before continuing to work with it. Without a check, errors can occur as described in the issues.
