### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, mkdir '/var/folders/f7/m9wvv5fn2_31l4wt3ds1pbdh0000gn/T...

### ISSUE THREAD

**Issue by jetteh22** [h3imdall/ftp-remote-edit#182]
[Enter steps to reproduce:]
Not sure how it happened.. Created a directory ("invoice_versions") and then another in that one ("v1") and then tried to create files in it and it threw this error.

Thought maybe it failed creating the files properly so I went through FileZilla FTP and deleted the files & directories and then created them through FileZilal FTP and tried to open them in Atom and it's still giving this error... Weird! 

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [ftp-remote-edit](https://github.com/h3imdall/ftp-remote-edit) package 0.12.11

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, mkdir '/var/folders/f7/m9wvv5fn2_31l4wt3ds1pbdh0000gn/T/4f819a2a/ftp.lpco.pro/public_html/clients/kcfl/invoice_versions/v1'

```
At fs.js:895

Error: ENOTDIR: not a directory, mkdir '/var/folders/f7/m9wvv5fn2_31l4wt3ds1pbdh0000gn/T/4f819a2a/ftp.lpco.pro/public_html/clients/kcfl/invoice_versions/v1'
    at Proxy.fs.mkdirSync (fs.js:895:18)
    at /packages/ftp-remote-edit/lib/helper/helper.js:30:18
    at Array.reduce (native)
    at createLocalPath (/packages/ftp-remote-edit/lib/helper/helper.js:27:11)
    at _FileView.open (/packages/ftp-remote-edit/lib/views/file-view.js:226:5)
    at /packages/ftp-remote-edit/lib/views/file-view.js:81:14)
    at HTMLLIElement.dispatch (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLLIElement.elemData.handle (/packages/ftp-remote-edit/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:19.3.0 ftp-remote-edit:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:16.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
autoclose-html 0.23.0 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
clock 1.9.0 
color-picker 2.2.5 
file-icons 2.1.17 
ftp-remote-edit 0.12.11 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
lipsum 0.1.0 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
seti-syntax 1.1.3 
seti-ui 1.10.0 
```

**Comment by FabrizioCaldarelli** [comment]
It seems as bash path /var/folders/f7/m9wvv5fn2_31l4wt3ds1pbdh0000gn/T/4f819a2a/ftp.lpco.pro/public_html/clients/kcfl/invoice_versions/ is a file and not a folder.

If this error will happen again, can you show output this command:

```
ls -l /var/folders/f7/m9wvv5fn2_31l4wt3ds1pbdh0000gn/T/4f819a2a/ftp.lpco.pro/public_html/clients/kcfl
```

**Comment by jetteh22** [comment]
What was weird is even after restarting Atom a few times it still gave the error. Restarting computer fixed it and it was working ok after that.

**Comment by FabrizioCaldarelli** [comment]
Maybe a file permission issue. If happens again, append the previous command output.

**Comment by cschindl** [comment]
Hi @jetteh22,

the error is thrown if a local directory cannot be created. This can be due to missing write permissions or an anti-virus program blocking access. The function only creates directories and not files. However, if a file with the same name as the directory to be created exists, an error is also thrown. The directories are created in the temporary user directory so that you should always have write access. Can it be that Mac OS X blocks access due to a security rule?

**Comment by cschindl** [comment]
A similar issue #162 has already been reported by a Mac OS X user.

**Comment by FabrizioCaldarelli** [comment]
I use Mac OS X and I never found this error.

**Comment by joerg** [comment]
I just gave a quite simple way to reproduce this in #192.
