### ISSUE TITLE
Reconnecting to server

### ISSUE THREAD

**Issue by snakerufus** [h3imdall/ftp-remote-edit#183]
Firstly, thanx for your great work.
This is, so far, the package I use the most. It's really helpfull.
I don't know if this is a real issue but, if I close Atom and the restart it, I loose my connection to server so I have to close all file I was working on and re-open them one by one after manually reconnecting to the server.
It would be great to have an auto re-connection to the server for all opened files on Atom restart.
Thank you so much!
Best regards

**Comment by leancode** [comment]
Seems to me this is a duplicate of https://github.com/h3imdall/ftp-remote-edit/issues/60

**Comment by cschindl** [comment]
Hi @snakerufus ,

the issue has already been reported in #60 but it is still open because implementation is very complicated and time consuming. I would be grateful for any help.
