### ISSUE TITLE
Terminal command to change the directory in tree view

### ISSUE THREAD

**Issue by linsea423** [h3imdall/ftp-remote-edit#185]
ftp-remote-edit is integrated well with Atom, so is the ide-terminal. A common working procedure is that ftp-remote-edit tree view on the left (or right), Atom editor on the top right (left), and ide-terminal at the lower right (or left). 

Whenever need to change to different folder and check/edit different files, **many clicks are made in the ftp-remote-edit tree view**. It will be **super helpful** if there is a ftp-remote-edit terminal command to change the directory and show the changed directory in the tree view. **It will eliminate numerous clicks and dramatically improve productivity.**

**Comment by cschindl** [comment]
Hi @linsea423,
 
I'm sorry I didn't understand your request. Ftp-remote-edit plugin does not have a terminal. The OS terminal should only have access to local files. A directory change of the ftp server is therefore not possible.

Am I misunderstanding?

**Comment by cschindl** [comment]
Hi @linsea423,

unfortunately I did not get an answer to my question. If there is no reply within the next week, I will close this.
