### ISSUE TITLE
Feature Request: Don't require password?

### ISSUE THREAD

**Issue by jetteh22** [h3imdall/ftp-remote-edit#188]
I'd love to have the option of not requiring a password to use ftp-remote-edit. It's just an unnecessary step for those of us who are not in a work environment where we have to worry about others accessing our servers.  With the open on startup features it would be nice to just have it automatically open without having to manually enter in the password. Any chance of getting this?

**Comment by thinkerman** [comment]
I forgot my password and now I'm stuck :-(

**Comment by cschindl** [comment]
@thinkerman If you have forgotten your password, there is unfortunately no way to access your data. You can only reset everything in the settings and start over. This time with an easier to remember password :)

**Comment by cschindl** [comment]
Hi @jetteh22 ,

your wish has already been suggested in #82. The great advantage of Ftp-Remote-Edit is that all access data are securely encrypted and protected against access by others. Since the plugin is open-source, it is not possible to implement internal encryption like other software, because all information is readable by everyone.

**Comment by thinkerman** [comment]
I found a way around it. I had to delete the config file on the computer and it asked me to add a new password. However the plugin times out and I have to restart Atom every so often. I'm not sure what the fix that is.

**Comment by ajostergaard** [comment]
@cschindl what about remembering the password for x days like many other programs? Or taking advantage of some OS level, or cross-platform, password or keystore? Inconvenient security creates risk.

Worth noting that in many cases (i.e. key only ssh without passwords) what is being encrypted is information freely available on the local computer already so there is literally zero additional security from encrypting the connection details (assuming ftp-remote-edit reads private keys from disk when it needs them like it should).
