### ISSUE TITLE
Password/Passphrase field bug.

### ISSUE THREAD

**Issue by mr660** [h3imdall/ftp-remote-edit#191]
"Password/Passphrase for authentication." keeps changing when  saving. When i save with password **** and edit again in the field i can see like 2 lines of stars and mini-scrollbar. I've seen this bug  like half year ago and it still comes back.

[printscreen](http://prntscr.com/j7tde8)

**Comment by cschindl** [comment]
Hi @mr660,

can you reproduce the error? We had a similar case before, but we could never reproduce it here, so we had no way to fix it.

**Comment by wacki4** [comment]
also can try to help if needed.

**Comment by cschindl** [comment]
Hi @wacki4,

I'm grateful for any help. Unfortunately I could never reproduce this error and therefore I could not solve it. So I don't know where to start.

**Comment by wacki4** [comment]
tried to reproduce it - without any luck. @mr660 do You maybe has any special chars in password? or something else? Is this problem still active?

**Comment by cschindl** [comment]
Since the error was not reproducible and many adjustments have been made to the configuration interface in the meantime, I will close the ticket here because the error no longer seems to exist.
