### ISSUE TITLE
Show Hidden Files - and - Hide Ignored Files - options not working

### ISSUE THREAD

**Issue by adrienrenaud** [h3imdall/ftp-remote-edit#197]
Using Ftp Remote Edit 0.12.12, both - Show Hidden Files - and - Hide Ignored Files - options are not working.
Regardless of the values set for those options, I always see all the files (hidden and ignored). 
![capture](https://user-images.githubusercontent.com/6208157/40682175-62d777de-638b-11e8-8c8f-45b2876f0659.PNG)
I'm on windows 7 connecting to an Ubuntu 16 on google cloud platform.

**Comment by cschindl** [comment]
Hi @adrienrenaud,

I think there's been a misunderstanding.

Tree View - Hide Ignored Files - Don't show items matched by the "Ignored Names" core config setting.
Tree View - Show Hidden Files - Force FTP Server to show hidden files (e.g. htaccess)

If you want to hide files/directories, you have to set the option "Hide Ignored Files" and adjust the "Ignored Names" core config setting.  These are located in the core atom settings. The package settings in your screenshot refer to the TreeViewFinder.
