### ISSUE TITLE
Stop bottom pane from opening on upload

### ISSUE THREAD

**Issue by steelstring94** [h3imdall/ftp-remote-edit#199]
Often (but not always) when I save a file and it uploads, a bottom pane opens giving me some kind of list of files.  I would like to have the option to disable this as it's annoying to always have to close it.

**Comment by cschindl** [comment]
Hi @steelstring94 ,

the bottom pane opens only in case of transfer errors. This is intended to show you the errors.

**Comment by steelstring94** [comment]
@cschindl okay, but it's really more annoying than helpful. It shows errors even though there are no problems and the files uploaded fine. It would be great to have the option to disable it.

**Comment by cschindl** [comment]
Hi @steelstring94,

the bottom pane opens only in case of transfer errors. However, we can add an option in the settings to deactivate the notification in case of errors.
