### ISSUE TITLE
Creating new folder, undefinedPath not found.

### ISSUE THREAD

**Issue by Quaked** [h3imdall/ftp-remote-edit#20]
Can browse and create files on FTP but can't create folders. Ideas?

**Comment by h3imdall** [comment]
Can you send the error log please. 
You can open the console with Strg+Shift+i. There you get the full error log.

**Comment by umiinside** [comment]
Hello!
At folder creation in ftp-remote-edit, gives out an error "undefinedPath not found". How to be?

**Comment by umiinside** [comment]
Made changes in view code ftp-remote-edit. Now during creation of the folder the error of "Path not found" appears. How to be?

**Comment by h3imdall** [comment]
I have merged the pull request from cschindl. 
@umiinside Was the directory created even though the error occurred?

**Comment by umiinside** [comment]
The mistake occurs even after update to version 0.11.2.

**Comment by cschindl** [comment]
After the folder is created, it tries to find and expand this folder in the tree. If the folder can not be found here, the above error message is output. To limit the error, I need the following information:

1. Which connection type do you use? FTP or SFTP (SSH)?
2. Do you use an initial directory?
3. Do you use the current atom version 1.17.0?
4. Is the folder created successfully?
5. Do you have the necessary permissions to create folders?
6. Can you find the folder after opening and closing the tree?
7. Does the path to the new folder contain non UTF-8-compliant characters?
8. Please tell me the used path, so I can adjust the situation.

**Comment by umiinside** [comment]
You have teamviewer? I can allow to you to look visually.

**Comment by umiinside** [comment]
Connection type: FTP
Initial reference book: the question did not understand
Current Atom version: 1.17.0 x64
The folder is not created.
Permissions: rights of the administrator. From the Aptana Studio program everything turns out.
Opening or closing of a tree: there is no folder is absent
Symbols not UTF-8: no
Way: / html/images as example

**Comment by umiinside** [comment]
I can give access to a hosting, for your full check.

**Comment by h3imdall** [comment]
@umiinside This would be great. Please send the credentials to  enigmadt+ftp-remote-edit@gmail.com

**Comment by cschindl** [comment]
Your data looks okay. It would therefore be great if you would send the owner the credentials, then I will look at the problem with him and hopefully find a solution. Please do not forget to replace the "[at]" with a "@" character when you send it :)

**Comment by umiinside** [comment]
Send you

**Comment by umiinside** [comment]
These parameters work in Aptana Studio 3. As is. The owner of a hosting will add nothing. 
If to use Aptana Studio 3, namely: http://www.aptana.com/products/studio3/download.html
Having installed the program it is possible to add the data of FTP sent you to its menu Window-> Show View-> Remote. And in this program everything works and is added that it would be desirable to see in your Package. It would be very convenient. Thanks.

**Comment by cschindl** [comment]
Thank you for the information. Today is a holiday in Germany. I will therefore be able to look at the problem on the Sunday at the earliest.

**Comment by umiinside** [comment]
OK

**Comment by cschindl** [comment]
@umiinside  I could find the mistake. When attempting to create a new folder, it is checked whether the folder already exists. A "list" command is sent to the FTP server. If the folder does not exist, an error message should be returned. Unfortunately the FTP server in your case does not report an error, but returns an empty list. This causes no new folder to be created. So I need to rewrite the FTP module. I have already started the correction, but this will take some time.

**Comment by umiinside** [comment]
Of course I will wait. But if you in the module make Refresh of the current folder, and also copying in clipboard of the file or folder with files, and an opportunity to insert these data in other place, would be very remarkable. And in general it was invaluable, bore it would be possible to move on a tree, chosen as a mouse, the folder or files. Then it is precisely possible to pass completely to Atom and to use your module. Thanks.

**Comment by cschindl** [comment]
@umiinside I commited all my changes and heimdall merged them into the current release. Can you check if the changes solves the issue? 

Please create a new ticket for every of your other feature requests. This makes it easier for us to deal with the open bugs and feature requests and help us to solve and close them separately.

**Comment by umiinside** [comment]
The problem about creation of folders is solved. Many thanks.
I will create new tickets.
Thanks.
