### ISSUE TITLE
[HELP] How to change the master password?

### ISSUE THREAD

**Issue by Andrewer11** [h3imdall/ftp-remote-edit#200]
IDK what was it pls help i tried to uninstall then reinstall the package but it not worked 
how to change or how to decrypt the password?

**Comment by Andrewer11** [comment]
you can change if you know the old password 
Settings > Keybindings > keymap file
and add to the end this
`'atom-workspace':
  'ctrl-b': 'ftp-remote-edit:change-password'
`
and if you press Ctrl And B it will show the menu to enter the old password and your new password

**Comment by cschindl** [comment]
Hi @Andrewer11,

The command to change the password (ftp-remote-edit:change-password) can be called via the Command Palette (ctrl-shift-p). There is no link in the menu. For this you need to know your old password. If you don't remember this, there is no way to restore your settings. Then you can only reset everything to factory defaults by deleting the fields "Encrypted Connections" and "Encrypted Password" in the settings of the plugin and restart atom.

**Comment by walldorff** [comment]
This worked! Thank you so much, Andrew!

Roland



Op do 2 aug. 2018 om 14:58 schreef Andrewer <notifications@github.com>:
