### ISSUE TITLE
Error message:  "Cannot read property 'next sibling' of undefined"

### ISSUE THREAD

**Issue by BigBlue219** [h3imdall/ftp-remote-edit#202]
While the FTP file structure is displayed on the right, opening some files causes an error message that says "Cannot read property 'next sibling' of undefined".   It seems to happen every time if I open a file that is the last one in a subdirectory.  However, it also happens on certain files that are not the last in the subdirectory.

When this happens, any changes to the file are not saved to the server.  There is no green box saying the save was successful, and the changes are not made.

The file actually does open, but only displays as a tab, and not in the "Open Files" on the left side of the screen.  This is a problem because I really like having them on the left.

When a file opens that doesn't have this message, it opens with no error message, appears in the "Open Files" pane, and saves with no issue

**Comment by cschindl** [comment]
Hi @BigBlue219 ,

can you post the error stack here so we can reproduce the situation?

**Comment by BigBlue219** [comment]
When the error occurs, the link for the error stack doesn't appear.  It simply shows a red box that says "Cannot read property of sibling 'undefined'."  The message disappears after a few seconds.  I tried putting the package in debug mode, but nothing goes to the console when this error appears.

In addition, I went to Developer Tools and watched the error log.  Nothing appears when this error message shows up.

Is there a way to see the error log a different way?  

Attached is a screencast showing what is happening.

[ftp-remote-edit.zip](https://github.com/h3imdall/ftp-remote-edit/files/2304341/ftp-remote-edit.zip)

**Comment by cschindl** [comment]
If debug mode is enabled, can you see in the developer tools (View->Developer->Toggle Developer Tools) if the download was successful? Please post a list of your other plugins. Maybe another plugin causes an error when opening the file and FTP-Remote-Edit just catches it and gives you the error message.

**Comment by BigBlue219** [comment]
Hello, I am still having this problem.  It occurs if adding a file that has the highest starting letter in the folder.  For example, if the folder has only one file called test.php, and you then create xxx.php, the error appears "Cannot read property of sibling 'Undefined.', because "x" is higher than "t."   If you create a folder, and then add a file of any name, the problem also occurs, presumably because it is the highest letter by default, since it is the only file.  Once this error occurs, you cannot save any changes to the file now or in the future - the green confirmation screen doesn't appear and there is no indication that it didn't save besides that.    I have been screwed more than once because I thought it was saving, and it wasn't.

I don't use Atom enough to fully understand what you are asking for.  I went to View | Developer | Toggle Developer Tools.  Are you asking for a copy of the console?

When there is an error:

tree-view.js? [sm]:333 connector:existsFile /account/staff/training/xxxxx.php
tree-view.js? [sm]:334 connector:connect
tree-view.js? [sm]:334 ftp:list
tree-view.js? [sm]:334 connector:disconnect
tree-view.js? [sm]:334 connector:disconnect
tree-view.js? [sm]:331 connector:uploadFile /account/staff/training/xxxxx.php /var/folders/_k/gydmjml55jg59q80nj03q3_80000gn/T/f03ebf1a/ftp.myserver.com/account/staff/training/xxxxx.php
tree-view.js? [sm]:334 connector:connect
tree-view.js? [sm]:334 ftp:list
tree-view.js? [sm]:334 connector:disconnect
tree-view.js? [sm]:334 connector:connect
tree-view.js? [sm]:334 ftp:put
tree-view.js? [sm]:334 connector:disconnect
tree-view.js? [sm]:331 connector:downloadFile /account/staff/training/xxxxx.php /var/folders/_k/gydmjml55jg59q80nj03q3_80000gn/T/f03ebf1a/ftp.myserver.com/account/staff/training/xxxxx.php
tree-view.js? [sm]:334 connector:connect
tree-view.js? [sm]:334 ftp:get
tree-view.js? [sm]:334 connector:disconnect



When there is not an error:

connector:existsFile /account/staff/training/aaa.php
tree-view.js? [sm]:334 connector:connect
tree-view.js? [sm]:334 ftp:list
tree-view.js? [sm]:334 connector:disconnect
tree-view.js? [sm]:334 connector:disconnect
tree-view.js? [sm]:331 connector:uploadFile /account/staff/training/aaa.php /var/folders/_k/gydmjml55jg59q80nj03q3_80000gn/T/f03ebf1a/ftp.myserver.com/account/staff/training/aaa.php
tree-view.js? [sm]:334 connector:connect
tree-view.js? [sm]:334 ftp:list
tree-view.js? [sm]:334 connector:disconnect
tree-view.js? [sm]:334 connector:connect
tree-view.js? [sm]:334 ftp:put
tree-view.js? [sm]:334 connector:disconnect
tree-view.js? [sm]:331 connector:downloadFile /account/staff/training/aaa.php /var/folders/_k/gydmjml55jg59q80nj03q3_80000gn/T/f03ebf1a/ftp.myserver.com/account/staff/training/aaa.php
tree-view.js? [sm]:334 connector:connect
tree-view.js? [sm]:334 ftp:get
tree-view.js? [sm]:334 connector:disconnect



I have a lot of installed packages, and am not sure how to easily produce a list of all of them, or to show how they may be interfering.

Please advise.  I do want to continue using this package, but this problem makes it almost unusable unless you add a file to every folder, called zzz.php, or create a blank file in an FTP editor first.

Thank you.

**Comment by cschindl** [comment]
Hi @BigBlue219,

to create a list of all plugins you can run this console command. This writes all plugins to a txt file:

`apm list --installed --bare > my-package-list.txt  `

With the list I could then try to recreate your configuration and identify the plugin that is causing the error.

**Comment by cschindl** [comment]
Hi @BigBlue219, 

I haven't received a package list from you yet, has the problem solved itself? If I don't get an answer, I'll close the issue here in a week.
