### ISSUE TITLE
fs is not defined

### ISSUE THREAD

**Issue by pu3antasyah** [h3imdall/ftp-remote-edit#203]
Error to save the FTP file through ftp-remote-edit. It's happens **after update to latest version** (0.12.13), every time error with messages` fs is not defined` while try to make changes by save the files.

ATOM
UBUNTU 16.04 LTS

**Comment by pu3antasyah** [comment]
take a look at `connectors/sftp.js` and `connectors/ftp.js`..

const defined as `FileSystem` . But at line `connectors/sftp.js:174` and `connectors/ftp.js:172` it declare `fs`. By changing this `fs` to `FileSystem`, issue fixed

**Comment by cschindl** [comment]
Hi @pu3antasyah,

thanks for pointing that out. Error has been fixed. Please update to the new version 0.12.14.
