### ISSUE TITLE
Permissions change after save

### ISSUE THREAD

**Issue by Duncank** [h3imdall/ftp-remote-edit#205]
Our server needs files to be not writeable by group; otherwise it throws php-errors, so my files are chmodded 644, but after every save of a file, it is changed to 666.

When I open the "file permissions" menu, it shows 644 (but that is probably old data), so when I save that, it works again. Any change FTP Remote edit could honor the permissions that are already in place?

Edit, some version numbers:
Atom 1.29.0
FTP-remote-edit 0.12.14
Windows 10
SFTP connection

**Comment by cschindl** [comment]
Hi @Duncank,

The upload will keep permissions of the source file. And the file on windows will always get 666. I think I need check the platform and prevent the behavior of permission preservation.
