### ISSUE TITLE
SSL/TLS required on the control channel

### ISSUE THREAD

**Issue by cukabeka** [h3imdall/ftp-remote-edit#207]
I get the error above for the a hoster. Might be the same as with this related plugin issue:
https://github.com/icetee/remote-ftp/issues/1131

**Comment by Aprania** [comment]
Please insert support for TLS/SSL in FTP connection. It's very important...

**Comment by cschindl** [comment]
FTPS support has already been added in relase [0.16.3](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.16.3). The control and data channels are encrypted. Therefore, this issue can be closed here.
