### ISSUE TITLE
Changed file privilege on save

### ISSUE THREAD

**Issue by Dallo71** [h3imdall/ftp-remote-edit#208]
Saving a remote file I found changed privileges.

```shell
# Before open on remote edit
root@Ubuntu1604:~# ll a.sh 
-rwxrwxrwx 1 root root 35 Aug 26 18:38 a.sh*

# After Save
root@Ubuntu1604:~# ll a.sh 
-rw-rw-rw- 1 root root 35 Aug 26 18:41 a.sh
```

how to reproduce:
- create a file.sh file on a remote machine
- chmod +x file.sh
- ope file.sh in atom by ftp-remote v.0.12.14 on Mac OSX High Sierra
- add text
- Save (Command+S)
- verify file.sh privileges

**Comment by cschindl** [comment]
The bug has already been posted in issue #205.
