### ISSUE TITLE
I suggest change keybinding shortcut

### ISSUE THREAD

**Issue by lichtner** [h3imdall/ftp-remote-edit#209]
Hi guys, I really like this plugin, but I suggest to change keybinding for `ftp-remote-edit:toggle` because `ctrl-space` is in all editor I know use for 'autocomplete' (also in atom) so then I have to change it in `keymap.cson`. It is no problem, but I think more users do it also. I suggest e.g. `ctrl-shift-c` (c like connections) it will be more user friendly.

**Comment by cschindl** [comment]
Since no one has commented on this, I think the proposal can be closed.
