### ISSUE TITLE
Files and folders with names starting with a dot not displayed

### ISSUE THREAD

**Issue by UFOcatcher** [h3imdall/ftp-remote-edit#211]
Hello there !

It seems that ftp remote edit doesn't display files and folders with names starting with a dot in the tree view.

For example, I can't see htaccess files nor .tmb folders in Atom but they are visible in FileZilla.

**Comment by cschindl** [comment]
Hi @UFOcatcher ,

try to set the following settings:

Tree View - Hide Ignored Files - Don't show items matched by the Ignored Names core config setting.
Tree View - Show Hidden Files - Force FTP Server to show hidden files (e.g. htaccess)

**Comment by UFOcatcher** [comment]
Hi @cschindl !

My bad I didn't think it would be an option to display those files or not.
Thanks for your help it worked !
