### ISSUE TITLE
No such file or directory error after creating a new file

### ISSUE THREAD

**Issue by RayFungHK** [h3imdall/ftp-remote-edit#212]
When I connected to Remote FTP server and try to create a new file, it prompt the error "No such file or directory", that it will make the remote file list stuck in loading stage, you cannot load any folder or file until you restart the Atom, it is very annoying.

**Comment by RayFungHK** [comment]
Hi @cschindl
I was connected via FTP, when I create a new file, I saw the console was stated upload success but download failed, and no file has created on server side.

**Comment by cschindl** [comment]
Hi @RayFungHK ,

I can not reproduce the error. Please activate the debug mode in the plugin settings, toogle the delevoper tools (Ctrl + Shift + i), open the "console" and copy the output here. Maybe this will help me find the error.

**Comment by RayFungHK** [comment]
![image](https://user-images.githubusercontent.com/6733398/46711145-a66deb80-cc7d-11e8-9e09-440411aa3846.png)
No error in console panel but the screen has shown file upload failed

**Comment by cschindl** [comment]
Was the remote file and the local file created? Possibly rights are missing on the server. New files are always created with 0644 on the server and then downloaded to the temp. user folder. I need to know if both fails.

**Comment by cschindl** [comment]
Please also check if the local path contains spaces and if the virus program prevents writing.

**Comment by RayFungHK** [comment]
@cschindl Does version 0.12.18 fixed this problem?

**Comment by cschindl** [comment]
@RayFungHK I'm still waiting for the answers to my questions. ;-) Version 0.12.19 doesn't fix this problem because I can't reproduce the error without your help.

**Comment by RayFungHK** [comment]
@cschindl before the updates, every is smooth, and I checked my Ubuntu configuration still have no idea what kind of module will cause this error...

**Comment by cschindl** [comment]
Since the FTP module has been completely rewritten, all open issues related to unsolved FTP problems will be closed.
