### ISSUE TITLE
Select when writing

### ISSUE THREAD

**Issue by ecpMasterHunterGTX** [h3imdall/ftp-remote-edit#213]
Hi.
First of all, thanks for your work in this application, it works perfectly for my needs.
I have a question about a functionality that I do not know if it has or not.
The questions is as follows:
For example, in filezilla, when you start writing, the application selects the directory file that matches what you are writing.
Does this feature have this Atom addon?
In case of having it. How is it used?
If it does not have that functionality, it would be good to implement it, because the option to look for files that have, overload the server because I have tens of thousands of files.

Thank you for your attention.

**Comment by cschindl** [comment]
Hi @ecpMasterHunterGTX ,

We are happy that you like the plugin. The built-in search (TreeView Finder) indexes the complete FTP server and then searches for files in the cached results. If there are too many files on your server, this can probably lead to the indexing taking forever and is therefore poorly usable. Unfortunately this is the only way to search for files. In the settings (TreeView Finder -> Ignored Names) you can exclude directories and files for indexing. Maybe this will help you. A search of the files by entering the name in the TreeView is unfortunately not possible. For servers with many files it is therefore advisable to create several entries with different initial directories.
