### ISSUE TITLE
Connection problem to pure-ftpd server

### ISSUE THREAD

**Issue by chcnetconsulting** [h3imdall/ftp-remote-edit#214]
Hi guys,

I have 2  projects on the same Shared Hosting server, all with pure-ftpd as FTP Server daemon.

The first project (wordpress site, normal ftp account) is working flawlessly. The second project simply doesn't work_
![image](https://user-images.githubusercontent.com/2822555/46077011-ab1ba580-c18f-11e8-999c-6509650699ed.png)

Although the login is successful, when downloading the filelist it keeps sending just 500 ? 500 ? 500 ? 
two pages long and then it closes the connection

![image](https://user-images.githubusercontent.com/2822555/46077104-fa61d600-c18f-11e8-9903-cbe2462e4e29.png)

How is it possible to debug that and fix it? Where could be the problem?

Thx for your help!

**Comment by cschindl** [comment]
Hi @chcnetconsulting ,

very strange. Can you send me the complete FTP protocol so I can see which command is sent to the server, which he doesn't seem to understand.

**Comment by chcnetconsulting** [comment]
On a fresh Atom installation on a new mac with a fresh ftp-remote-edit everything was fine. Only ftp accounts – this seems to work, also that

What I did was to setup on the old mac the first account with FTP, the second with scp enabled (missing 0x02 and 0x04) and then because of the failed scp connection, I wanted ftp again, but this didn’t work anymore 😉

Could you navigate me, how to get the ftp protocol out of atom? – I wasn’t able to debug the session

Von: Carsten Schindler <notifications@github.com>
Antworten an: h3imdall/ftp-remote-edit <reply@reply.github.com>
Datum: Dienstag, 9. Oktober 2018 um 18:59
An: h3imdall/ftp-remote-edit <ftp-remote-edit@noreply.github.com>
Cc: Chcnet Firma <office@chcnet.at>, Mention <mention@noreply.github.com>
Betreff: Re: [h3imdall/ftp-remote-edit] Connection problem to pure-ftpd server (#214)


Hi @chcnetconsulting<https://github.com/chcnetconsulting> ,

very strange. Can you send me the complete FTP protocol so I can see which command is sent to the server, which he doesn't seem to understand.

**Comment by cschindl** [comment]
Hi @chcnetconsulting, 

please activate the debug mode in the plugin settings, toogle the delevoper tools (Ctrl + Shift + i), open the "console" and copy the output here.

Unfortunately, the FTP protocol cannot be copied. It is what you have already sent as a screenshot. All commands sent to the server start with this character ">" and all received responses start with this character "<". I need the sent command before the reply with the many 500 ? errors. It's best to take another screenshot, but this time with more output.

**Comment by cschindl** [comment]
Since the FTP module has been completely rewritten, all open issues related to unsolved FTP problems will be closed.

**Comment by chcnetconsulting** [comment]
I have mentioned this already. Very cool work!

Mit freundlichen Grüßen

CHCNET Hosting & Coding
Christoph Christ
Wienerstrasse 23
A.2410 Hainburg/Donau

Tel: +43-2165-93059
Fax: +43-2165-93059 - 339
Mobil: +43-664-2382384

UID-Nr: ATU61214947
email: office@chcnet.at
