### ISSUE TITLE
Suggestion: Let us move files

### ISSUE THREAD

**Issue by dominotrix** [h3imdall/ftp-remote-edit#217]
You can drag & drop a single file or folder into another one to move it, but if you have 30 files you need to move, you must do it one by one.

Can we select multiple files with Ctrl+Click on them, and then drag them to the folder we want? Also, single left click-opening a file is a bit off. Missclicking them, or (if you make this suggestion above) Ctrl+Click would lead to opening the file. 

- Double clicking on a file to open it would be nice.
- Double clicking to enter a folder would be better.
- Ctrl + Click selects multiple files (or folders too).
- Shift + Click selects multiple files in a row.

If all these are not a quality-of-life improvement in your opinion, at least let us have a command console so we can move files manually from server console.

**Comment by cschindl** [comment]
Hi @dominotrix ,

the handling is based on the TreeView plugin, which creates the project pane. The selection of files and directories is done in the same way. The option "Allow Pending Pane Items" can be deactivated in the plugin settings, which means that files are no longer opened as a preview by a single click, but are opened permanently by a double click. The selection of several files would certainly be an improvement but the plugin would have to be modified at many places. Unfortunately I don't have the time for that at the moment. Therefore I would be very grateful for help ;)
