### ISSUE TITLE
Unable to edit your current password

### ISSUE THREAD

**Issue by Berumen95** [h3imdall/ftp-remote-edit#219]
I forgot my current password, I do not know how to recover it, there isn't a recover option, I have been delete all the configuration settings for restart the service and set a new password, but this is to long and tedious, just put a new recovery button or something like that.

Thanks for ur attention.

**Comment by cschindl** [comment]
Hi @Berumen95,

restoring a forgotten password is not possible, only resetting to factory defaults. I agree with you that this could be made easier with a button. For this I could also open a new feuture request or rename it here so that it corresponds more to the content.
