### ISSUE TITLE
Local changes are wiped

### ISSUE THREAD

**Issue by barnlight** [h3imdall/ftp-remote-edit#222]
Steps to reproduce:

- Connect to server
- Create test.html, type "1" into file and save
- (File is uploaded)
- Close file, open from local cache (C:\Users\%user%\AppData\Local\Temp\%hash%\%host%\var\www\mywebsite\test.html)
- Modify file with "2" and save
- (File is not uploaded?)
- Close file, open file from Ftp-Remote-Edit
- File contents reverts to "1" and local file contents are replaced

**Comment by cschindl** [comment]
Hi @barnlight, 

yes the behavior is correct, this plugin does not monitor the file directory for changes. It simply sets a handler in atom when saving a file opened by the plugin, which then triggers the upload. Each time you reopen the file from the (S)FTP server using the plugin, it is downloaded and opened in atom. This will overwrite local changes. The local files are temporary files and should not be edited outside of atom. This plugin is used to edit files directly on the (S)FTP server. 

If you want to edit a local copy of the files on your computer and then synchronize them, I would recommend that you try the plugin "remote-ftp". This plugin always creates a full copy of all the (S)FTP files in a local project and then synchronizes all changes.
