### ISSUE TITLE
Servers backup

### ISSUE THREAD

**Issue by marclight** [h3imdall/ftp-remote-edit#225]
First, thanks for your package, very well made.

Is there a way to backup the servers list to restore in another installation?  If not, it would be a nice feature.

**Comment by cschindl** [comment]
Hi @marclight ,

all plugin settings are stored in the atom configuration file (config.cson). You can find it in the menu under "File" - > "Config". You only have to save this file and copy it into your new installation to restore all your settings including your server list.

**Comment by nocturnalguru** [comment]
This should be added to the README.md file as a feature!  This would have saved me a lot of time.  Great work on the app.
