### ISSUE TITLE
Can login but cant find main directory?

### ISSUE THREAD

**Issue by Fleepy** [h3imdall/ftp-remote-edit#227]
When i use Filezilla, everything works fine. i can see everything inside.

But when i use the ftp package, It logs in, shows the one directory that has all the files in it, and says
"The system cannot find the file specified."

Any fix for this?
FTP server is hosted by Nitrous-networks incase you wanted to know.
and its being controlled by TCAdmin

**Comment by cschindl** [comment]
Hi @FloopyDisk,

to find in the error I need the output of the developer mode console and the FTP status codes from the FTP log.

**Comment by cschindl** [comment]
Is there any new information? Otherwise I will close the issue here in a few days.
