### ISSUE TITLE
Feature: Open specific file, not via tree

### ISSUE THREAD

**Issue by robertandrews** [h3imdall/ftp-remote-edit#230]
How about a way to open a specific file on command?
You see, one of my remote directories contains a great many files, and loading them all in to the folder tree when it is expanded takes a lot of memory. In fact, there are so many that I cannot even locate the one I want. I need to jump-start to it.

**Comment by cschindl** [comment]
Hi @robertandrews,

Have you already tried to find the file using the built-in finder? Right click on the server and select "Find file" or use the shortcut ctrl-alt-p.

**Comment by robertandrews** [comment]
No. Thanks. I didn't know about that.
Are directories cached once indexed? Because I'm seemingly up to 42,000+ files so far during indexing.

**Comment by cschindl** [comment]
Yes the index is cached. You can also exclude directories from indexing in the plugin settings.
