### ISSUE TITLE
Quitting atom loses existing servers

### ISSUE THREAD

**Issue by cnrmck** [h3imdall/ftp-remote-edit#232]
When I quit atom I lose the servers that I have set up. It most recently happened when I upgraded to the most recent version of ftp-remote-edit, but it has failed for me when I have just done a standard restart. 

I was on version 0.12.20 when the failure happened. I'm using a Mac and Atom version 1.32.1. Not sure why it's happening, but it's very frustrating because I had loaded about 4 other ssh connections and now all I have is the original one that I had. 

I'll try purging the package and reinstalling and report if that fixes the problem, might be old files messing stuff up.

Update -- It just happened to me again. It's really annoying because I have about 5 devices I ssh into regularly and when I reopen Atom after restarting my computer or after an update I only see one of my devices remaining. I tried uninstalling and reinstalling, if anyone has a recommendation for a more aggressive way to remove old files that may be causing the issue I'm open to trying it. 

Update -- I feel really stupid. It may have just been that I wasn't hitting the 'save' button when editing servers, I may have just been clicking out of the window and then assuming that when it work it was also saved. 

I will test when I have another opportunity, but I don't want to take the risk of having to reinput the servers right now.

**Comment by cschindl** [comment]
Hi @cnrmck,

to save the settings permanently in the atom configuration file, you have to click on the "save" button. Only here settings are written to the configuration. A restart only reads the settings. An overwrite on restart is excluded.
