### ISSUE TITLE
Some directories don't show up.

### ISSUE THREAD

**Issue by daron4ever** [h3imdall/ftp-remote-edit#234]
Check the screenshot below:
https://www.dropbox.com/s/uioqu7qny7b4mxl/Screenshot%202018-12-05%2020.53.45.png?dl=0

It supposed to be included apps, htdocs, stack folders, but your package didn't show them in the tree. Screenshot: https://www.dropbox.com/s/ctfi1kfpdmghjwl/Screenshot%202018-12-05%2020.53.54.png?dl=0

Did I miss something?

Thanks.

**Comment by cschindl** [comment]
Hi @daron4ever,

Do you connect via FTP or SFTP? With FTP it can happen that the server hides some directories. Please activate the option "Show Hidden Files" in the plugin settings. Also check if the directories do not appear in the list of ignored directories/files in the atom core settings and in the plugin settings under "Hide Ignored Files".

**Comment by daron4ever** [comment]
Hi @cschindl,

I connect via SFTP using SSH and ticked "Show Hidden Files".

Any solutions you might have?

Thanks.

**Comment by daron4ever** [comment]
Hi @cschindl,

I tested your plugin and remote-ftp plugin with mostly default options.

The remote-ftp plugins showed the directories that didn't show at your plugin.
I also checked Cyberduck, they showed the directories.

So, I think it's a permission problem as you said but not the server side.

Thanks.

**Comment by cschindl** [comment]
Hi @daron4ever,

the only other explanation would be that the directories which are not displayed to you are symlinks and not real directories. This plugin ignores symlinks and displays only files and real directories. Could this be the reason?

**Comment by daron4ever** [comment]
That's fine. Thank you for the answering.
