### ISSUE TITLE
some kind of encoding issues

### ISSUE THREAD

**Issue by ssfrr** [h3imdall/ftp-remote-edit#237]
I'm having trouble getting `ftp-remote-edit` working. First, I assume that if I give a private SSH key and select "use sftp" then I don't need a username and password, right? But then connecting gives an error: 

"expected 0x2, got 0xa7".

If I put in my username and password I get an error:

"encoding too long"

instead.

Maybe related: whenever I save the server settings I see a warning in the console: "internal/process/warning.js:18 (node:11022) Warning: Use Cipheriv for counter mode of aes-256-ctr.

**Comment by ssfrr** [comment]
any ideas how I could start debugging this? For some reason the error messages don't have the backtraces that Atom error messages usually have, so I can't tell where they're coming from or dig in to try a fix.

**Comment by cschindl** [comment]
Hi @ssfrr,

The private key file must be in OpenSSH format.

passphrase - For an encrypted private key, this is the passphrase used to decrypt it.

**Comment by ssfrr** [comment]
Whoops - I got my keys mixed up and it turns out that RSA key does have a passphrase. I think the only issue here is already a known upstream issue, so I'm closing.
