### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by marcellribeiro** [h3imdall/ftp-remote-edit#238]
Hello!

Whenever I open a file it gives the 'Unknown error' error and then when I click again it normally opens the file.

I have already reinstalled and the error repeats.

ftp-remote-edit 0.12.21
atom 1.33.0
windows 10

**Comment by cschindl** [comment]
Hi @marcellribeiro,

can you please tell me if the error occurs right after the connection starts or later? Do you use FTP or SFTP for the connection?

**Comment by marcellribeiro** [comment]
Hi @cschindl,

The error occurs later the connection starts, only happens when I click to open a new file.

SFTP connection.
