### ISSUE TITLE
Cannot parse privateKey: Unsupported key format. Is ed25519 supported?

### ISSUE THREAD

**Issue by adamryczkowski** [h3imdall/ftp-remote-edit#243]
When I try to connect to the localhost (to test the plugin), I get the error message `Cannot parse privateKey: Unsupported key format`. 

### Steps to Reproduce
1. Install Ubuntu 16.04
2. Install current atom using the apt protocol, as documented on https://flight-manual.atom.io/getting-started/sections/installing-atom/
3. Install the `remote-ftp` inside atom
4. Select Packages->Ftp-Remote->edit servers...
5. Fill in to connect using `ssh:` on `localhost` (just to test the addon) as in the ![screenshot from 2019-01-09 09-22-35](https://user-images.githubusercontent.com/4469707/50886322-6e975100-13f0-11e9-99a1-b0c369044f6a.png)
6. When double-clicking the `localhost` entry in the `Remote` view, I get the error `Cannot parse privateKey: Unsupported key format`.

I can login to the `localhost` using that key (without typing the password) from shell using `ssh localhost`.

### Versions
Atom 1.34.0,
Ubuntu 16.04.5 LTS

**Comment by cschindl** [comment]
Hi @adamryczkowski,

we've had a similar request before. Please take the information from the old issue. https://github.com/h3imdall/ftp-remote-edit/issues/237#issuecomment-448358943

**Comment by Szlavicsek** [comment]
I can't even open the server settings modal... After pressing ctrl + space and entering my password, nothing happens. No tab in tree view is visible, and can't make Edit Servers work from the command palette either. I'm using atom 1.34 on win 10. What am I doing wrong?

**Comment by cschindl** [comment]
Hi @Szlavicsek ,

since your request has nothing to do with this topic, please create a new issue for your problem.

**Comment by cschindl** [comment]
Hi @adamryczkowski,

did the information from the old issue help you? If so, I will close this ticket here.

**Comment by adamryczkowski** [comment]
Do you mean:
>Whoops - I got my keys mixed up and it turns out that RSA key does have a passphrase. I think the only issue here is already a known upstream issue, so I'm closing.

Of course, it does not help. I don't use RSA and obviously I don't have a passphrase. I wrote that "I can login to the localhost using that key (without typing the password) from shell using ssh localhost.".

Anyway, thanks for asking. If you have time, can you please tell me, a) if the ed25519 is supported, b) is my platform supported (it is not written in the docs) and if both are yes c) is it a bug or a feature.

**Comment by adamryczkowski** [comment]
Sorry I misread the link. The comment #237 was referring to the fact that `ftp-remote-edit` supports key in the PEM format. 

I Googled up (https://security.stackexchange.com/questions/139918/generate-pem-key-file-from-ed25519-pub-file) that PEM format is fundamentally incompatible with modern and recommended digital signature scheme ed25519 for remote logging via SSH. 

Are there any plans to change that?

**Comment by cschindl** [comment]
The changes would have to be made in the SSH library (https://github.com/mscdex/ssh2/issues/352) used. There is already an issue for this. Unfortunately this seems to still not be implemented despite great demand. Maybe you are trying to ask here again.

**Comment by surak** [comment]
According to them, it is: https://www.npmjs.com/package/ssh2
```node.js -- v5.10.0 or newer
node v12.0.0 or newer for Ed25519 key support```

**Comment by surak** [comment]
But I end up with `Handshake failed: no matching client->server HMAC`

So, the ssh2 library being used on ftp remote edit (I'm checking mine, it's 0.8.9 as of 16.june.2020) DOES support this kind of key. I don't know how to fix it here.
