### ISSUE TITLE
The URI handler is wonderful. I would like to add functions.

### ISSUE THREAD

**Issue by kamihicouki** [h3imdall/ftp-remote-edit#244]
Thank you very much for making such a wonderful plugin.

I found a function called "URI handler" a while ago.
This function is very powerful when used on a team.
However, please add only one function.

1. If you write PATH, I want that PATH to be ROOT

[FTP URLs] (http://jkorpela.fi/ftpurl.html)

In the item "The syntax of FTP URLs" above, there is a description that includes "path" in the URI.
I tried to open Atom and ftp-remote-edit with the following URI, but no migration of the directory and rewriting of the root path were executed.

Thank you for your consideration.

**Comment by cschindl** [comment]
Hi @wacki4,

Would it be possible for you to integrate the changes for us?

**Comment by wacki4** [comment]
I will try to look at this in free moment - i think it would be possible.

**Comment by wacki4** [comment]
Done, sent pull request #245
