### ISSUE TITLE
[Feature Request] Clone file

### ISSUE THREAD

**Issue by jar812k6** [h3imdall/ftp-remote-edit#248]
It would be great to have a Clone File option in the context menu. 

When I need an exact copy of a file, I currently have to copy to the same folder then rename the copied file. 

It would be more efficient to just click a "Clone" option from file menu context and be prompted for the new filename. Which should result in an exact copy of the file selected with the new name entered.

**Comment by cschindl** [comment]
Released in [0.13.0](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.13.0)

**Comment by jar812k6** [comment]
Thank you for including this in your most recent release cschindl! 

However, I believe I have noticed some unexpected functionality. When I click "duplicate", it's only creating a new file with the name I specified. I would expect the new file to contain the duplicated file contents with the new name I have selected, no?

**Comment by cschindl** [comment]
That's correct. He should download the file and then upload it again with a new name. The content of the file should therefore be the same. Can you please check in the log or in the debug mode in the console whether it does this with you?

**Comment by jar812k6** [comment]
After further review, I can confirm it does indeed work as you stated and downloads the file then reuploads again with the new name. 

However, after that action the new file tab is opened with blank contents. If I close the file and re-open it contains the contents as expected. 

I believe that the new file tab opened from the duplicate trigger should display the new file contents instead of blank.

**Comment by cschindl** [comment]
I have released a new version. Please test it.

**Comment by jar812k6** [comment]
I can confirm it works perfectly in 0.13.2. Thank you very much for the quick resolution!
