### ISSUE TITLE
Drag-and-drop

### ISSUE THREAD

**Issue by umiinside** [h3imdall/ftp-remote-edit#25]
Hello!
One more convenient thing in your Package if it was possible to carry out Drag-and-drop of folders with their contents or files, in other branches of projects.
Then it is possible to pass precisely completely with Aptana Studio and to work full-scale in Atom.
Thanks.

**Comment by umiinside** [comment]
Hello!
And prompt this a post subject you plan to do or not?
As without this functionality, not sense to look towards ID Atom,
because to have to copy or postpone, to today in Aptana Studio.
Thanks.

**Comment by flamebeard** [comment]
any info on when this will be released?

**Comment by cschindl** [comment]
Hi @flamebeard, 

Drag-and-drop of files and directories within a server works fine. Only the upload of local files to the FTP server #138 is not implemented yet and will take some time. Moving files from one server to another is too complicated, so it will probably not be implemented in the foreseeable future.
