### ISSUE TITLE
[Feature Request] Keyboard shortcuts for context-menu actions

### ISSUE THREAD

**Issue by peter-webbird** [h3imdall/ftp-remote-edit#250]
I would like to see keyboard shortcuts for context-menu actions on remote files and folders implemented in a future version.

This could include:
 - Rename [F2]
 - Delete [Del -or- Backspace]
 - Copy [Ctrl + C]
 - Cut [Ctrl + X]
 - Paste [Ctrl + V]
 - New file [A]
 - New Folder [Shift + A]

Ideally this would work similarly to the built-in keyboard shortcuts in the Tree View for local files, with a preview of the shortcut displaying in grey in the context menu.

**Comment by cschindl** [comment]
Released in [0.13.0](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.13.0)
