### ISSUE TITLE
Connection Issue - Unknown command

### ISSUE THREAD

**Issue by davidmicallef82** [h3imdall/ftp-remote-edit#254]
I just upgraded to 0.13.0 - before the upgrade, everything was working fine.  After the upgrade, i reset atom and when i go to connect to any of my FTP i get an unknown command error.

**Comment by cschindl** [comment]
Hi @davidmicallef82,
 
I have updated the FTP library. It may contain an error. Can you please post the FTP protocol here so I can find out which FTP server you are using and which command it doesn't know. In the meantime you can go back to the old version with "apm install ftp-remote-edit@0.12.23".

**Comment by davidmicallef82** [comment]
Hi @cschindl 

The protocol I am using is FTP with a logon type of username / password.  Here is a pic of the error (
![image](https://user-images.githubusercontent.com/43555473/52917778-7cbb8400-3343-11e9-9e24-da7a4428fa41.png))


I also noticed I am getting an error when I start atom too (it flashes on the screen).  I have attached below it. Hope it helps.
![untitled](https://user-images.githubusercontent.com/43555473/52917752-40882380-3343-11e9-91ca-81a4304cfcaa.png)

Cheers

**Comment by cschindl** [comment]
Can you upload a screenshot of the FTP protocol? You can find it under the server list. It is one line by default but you can resize it.

![log](https://user-images.githubusercontent.com/28109094/52918010-3a1d8b80-32f2-11e9-8691-1b8dd98e6367.jpg)

**Comment by davidmicallef82** [comment]
Hi,

Yes will do.  I am at work so I will do it when I am back at home.

Cheers

**Comment by davidmicallef82** [comment]
![connection](https://user-images.githubusercontent.com/43555473/52933855-c38f9500-33a8-11e9-9317-e79238e5bdeb.jpg)

**Comment by cschindl** [comment]
Unfortunately I had to downgrade the FTP library again, because the PureFTP server causes problems with the EPSV command. This is standard since 1998 but still not supported everywhere ;) Please check if everything works as usual now.

**Comment by davidmicallef82** [comment]
I upgraded again but same error.

![connection](https://user-images.githubusercontent.com/43555473/52954170-8db8d380-33dd-11e9-93ca-625af867c7b1.jpg)

I needed to downgrade again for it to work.  Happy to keep testing for you in the morning

**Comment by cschindl** [comment]
I think the library wasn't downgraded correctly when atom upgraded the plugin. Can you please try uninstalling the plugin first and then reinstalling the current version? Don't worry. Your server settings will be preserved.

apm uninstall ftp-remote-edit
apm install ftp-remote-edit

**Comment by cschindl** [comment]
I have released a new version. Please test it.

**Comment by davidmicallef82** [comment]
Works now :)
