### ISSUE TITLE
Unfavorable shortcut (command + space) for macOS

### ISSUE THREAD

**Issue by welove** [h3imdall/ftp-remote-edit#256]
The shortcut (Command + Space) to open FTP-Remote doesn't work on the Mac because it always brings up macOS  spotlight!

option/alt + space like it was before was better

**Comment by cschindl** [comment]
Hi @welove, 

in the last version 'ctrl-space' was used according to config. Are you sure that macOS used 'option/alt + space' earlier? Unfortunately I can't test this because I don't have macOS.

**Comment by welove** [comment]
Now I'm not sure, but I think you are right!
It used to be "ctrl+space"

**Comment by cschindl** [comment]
Released in 0.13.3. Thanks for the hint. Please update.
