### ISSUE TITLE
Connection ends when ftp open for a while

### ISSUE THREAD

**Issue by masoodanwar85** [h3imdall/ftp-remote-edit#258]
Connection ends automatically after a while when working on ftp files. The files does not get saved. When I try to re-open the connection, it keeps spinning but nothing happens. If I open other ftp connections, they work fine.
For first connection to work, I have to close the atom and restart to work.

**Comment by cschindl** [comment]
Can you please enable the debug mode? To enable the debug mode please go to the atom settings and look for the package "ftp-remote-edit". Here you have to click on settings. Please activate the checkbox for debug mode. Then you can open the console via the menu "View" -> "Developer" -> "Toggle Developer Tools". The debug messages should be displayed in the console.

In addition, all FTP commands are also displayed in the FTP log below the server list. This can also be expanded. If the error occurs, it would be a good idea to post a screenshot of the FTP log and the debug messages from the console here. I could then try to reproduce the error and try to correct it.

**Comment by masoodanwar85** [comment]
Attached is the screenshot.
1. Left FTP Pane (The loading icon keeps spinning forever, but does not load directories/files)
2. Remote Transfer Log (The file status is 'Waiting')
3. Console is also open for your help.
![screenshot from 2019-02-27 03-27-03](https://user-images.githubusercontent.com/3944504/53452299-ba569600-3a42-11e9-87fe-507955f78a7c.png)

**Comment by masoodanwar85** [comment]
By the way! this usually occurs when I put my computer to sleep with files opened.

**Comment by cschindl** [comment]
Thanks for the info. I could not reproduce the error in Windows unfortunately. It seems that he loses the FTP connection but doesn't notice this and doesn't try to reestablish the connection. It may be that it is something OS specific. I will install linix mint on a vm and try to reproduce the error. The FTP log what I meant in addition is not the transfer log. The ftp log can be found directly under the server list. Here you see in the screenshot "> NOOP". You can extend this one line to see the whole log.

**Comment by cschindl** [comment]
I was able to reproduce the error. If the connection is terminated, this is unfortunately not recognized. I have fixed the error. It is now checked if there is a timeout after 30s for the connection. In the next release everything should work again.

**Comment by cschindl** [comment]
Changes are now included in the new release ([0.13.5](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.13.5)).

**Comment by cschindl** [comment]
@masoodanwar85 Please check if the timeout is detected after 30s and the problem has been fixed.

**Comment by masoodanwar85** [comment]
@cschindl Yes, now the problem has been fixed. Thanks
