### ISSUE TITLE
Incompatible with Atom material UI

### ISSUE THREAD

**Issue by shipengcheng1230** [h3imdall/ftp-remote-edit#261]
Hello, when I use material UI, the configuration window is somehow shadowed like below:

![image](https://user-images.githubusercontent.com/11856151/53686799-30385700-3cfa-11e9-8e15-11402b5edda4.png)

Thank you for such amazing package!

**Comment by cschindl** [comment]
Changes are now included in the new release ([0.14.0](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.14.0)).
