### ISSUE TITLE
Can't Edit Severs

### ISSUE THREAD

**Issue by cpreston321** [h3imdall/ftp-remote-edit#27]
Every time you try to edit it does not show the whole menu 

![glitch](https://cloud.githubusercontent.com/assets/6619884/26835532/7afaa862-4aa6-11e7-8681-8f46d078158e.PNG)

**Comment by cschindl** [comment]
Hi @cpreston321,

this looks like a display error. All activated packages can load your own stylesheets. These can therefore have a negative effect on each other. Please tell us your activated packages so we can find the package that caused this error. Then we can customize our stylesheets.

**Comment by cschindl** [comment]
Hi @cpreston321,

unfortunately I have no feedback from you. If I do not hear anything new from you, I will close this issue next week.
