### ISSUE TITLE
[Feature Request] Additional using .ftpconfig for managing connections

### ISSUE THREAD

**Issue by Olli** [h3imdall/ftp-remote-edit#270]
Using .ftpconfig files enables the user to switch seamlessly from the remote-ftp plugin to this plugin without adding all the connections by hand.

**Comment by cschindl** [comment]
Hi @Olli,

so do you suggest that you manually want to import the .ftpconfig file to apply the settings?

**Comment by Olli** [comment]
Importing is one thing. The cool version is the "just use the existing .ftpconfig". I assume the latter will be the more complex one.
My problem is that I use remote-ftp with per project .ftpconfig files but I want to switch to ftp-remote-edit.
The non existing encryption of the credentials isn't a big problem cause tools like filezilla also don't really encrypt (IMHO).

**Comment by wacki4** [comment]
How would You like it to work? This plugin has diffrent workflow than remote-ftp, it operates on remote files, not syncing with local project.

**Comment by Olli** [comment]
Hm maybe check for .ftpconfig and if the .ftpconfig is present there appears a "virtual" server in the accountlist. That account is useable like all other accounts and has a option for importing the credentials to make this account permanent. 
The "virtual" server disappears if the project is changed or closed.
I don't know if this is doable.

**Comment by wacki4** [comment]
But 'where' is .ftpconfig present ? :) We don't operate on project panel, so where to look for it? Entire harddrive? :)

I think that importing this file is doable.

**Comment by Olli** [comment]
Oh ok then it seems more complicated to look for a .ftpconfig. 
But plain importing would be a huge help too.

**Comment by wacki4** [comment]
I'm working now on filezilla import. If there would be everything allright, i will add also .ftpconfig import, it is really more simpler ;)

**Comment by Olli** [comment]
Cool. I'm looking forward. Thx so far :)

**Comment by wacki4** [comment]
@cschindl as i know You can also close this ticket ;) Done at 16.0
