### ISSUE TITLE
"toggle panel" without closing tree view 

### ISSUE THREAD

**Issue by AlekseyGur** [h3imdall/ftp-remote-edit#271]
Hello.
Thank you one more time for creation such a great tool!

Just upgraded ftp-remote-edit from v.0.12 to 0.14. I liked folders for servers - nice idea! But now there is a problem with toggling of panel. In v.0.12 I could press ctrl+space to hide panel and get some more monitor space for code editor. But now if I press ctrl+space then panel closes together with tree of files. And next time when I press ctrl+space to show panel I have to open all folders again. 

In v.0.12 I liked that I press ctrl+space and hide/show panel without closing tree of files. 

Please, don't close opened folders. ctrl+space worked better in v.0.12.

Best regards, 
Alex.

**Comment by cschindl** [comment]
Changes are now included in the new release ([0.14.2](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.14.2)).
