### ISSUE TITLE
Cannot parse privateKey

### ISSUE THREAD

**Issue by xjustalecsx4** [h3imdall/ftp-remote-edit#275]
Hi,

Cannot parse privateKey: PPK private key integrity check failed 

help, pls?

**Comment by cschindl** [comment]
Hi @xjustalecsx4,

FTP-Remote-Edit uses the [ssh2 ](https://github.com/mscdex/ssh2)library, which currently only supports private keys in OpenSSH PEM format. Please check if your private key is in the correct format. Further help can also be found in the issues of the SSH library.

**Comment by sebafurfaro** [comment]
> Hi @xjustalecsx4,
> 
> FTP-Remote-Edit uses the [ssh2 ](https://github.com/mscdex/ssh2)library, which currently only supports private keys in OpenSSH PEM format. Please check if your private key is in the correct format. Further help can also be found [here ](https://github.com/h3imdall/ftp-remote-edit/issues/237)or in the issues of the SSH library.

Hi, I've the same problem and my private key its ok. Before the last update, FTP-Remote-Edit was working ok. Any recomendation?
