### ISSUE TITLE
I am using ATOM Ftp-Remote-Edit.

### ISSUE THREAD

**Issue by nagadas** [h3imdall/ftp-remote-edit#276]
I am using ATOM Ftp-Remote-Edit.

What is the bug in FileZilla when it is connected but not in Ftp-Remote-Edit?

Ftp-Remote-Edit can not connect to specific sites.

**Comment by cschindl** [comment]
Hi @nagadas,

to help you we need more information. What error message do you get when trying to connect? How do you try to connect (FTP or SFTP)? Do you use a password, private key or ssh agent? 

Please enable the [debug mode](https://github.com/h3imdall/ftp-remote-edit#package-preferences) in the plugin settings and open the development console in Atom. Here you can see the DEBUG output.

**Comment by nagadas** [comment]
This is what you see in the Developer Console.

I would really appreciate your help.

--------

internal/process/warning.js:18 (node:166564) Warning: Use Cipheriv for
counter mode of aes-256-ctr
writeOut @ internal/process/warning.js:18
VM22 <embedded>:14 Installing package atom-ftp-editor failed Error:
Installing “atom-ftp-editor@0.5.0” failed.
    at
C:\Users\nsh\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:899302
    at r
(C:\Users\nsh\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:893754)
    at o
(C:\Users\nsh\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:1033430)
    at ChildProcess.n.process.on.e
(C:\Users\nsh\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:1033636)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit
(internal/child_process.js:198:12) Failed to install atom-ftp-editor
because Git was not found.

The atom-ftp-editor package has module dependencies that cannot be
installed without Git.

You need to install Git and add it to your path environment variable in
order to install this package.

You can install Git by downloading, installing, and launching GitHub for
Windows: https://windows.github.com

Run apm -v after installing Git to see what version has been detected.

(anonymous) @ VM22 <embedded>:14
VM22 <embedded>:11 Error deactivating package 'multiple-remote-ftp'
TypeError: Cannot read property 'destroy' of null
    at Object.deactivate
(file:///C:/Users/nsh/.atom/packages/multiple-remote-ftp/lib/multiple-remote-ftp.js:60:21)
    at Package.deactivate
(C:\Users\nsh\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:3026335)
    at PackageManager.deactivatePackage
(C:\Users\nsh\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:384083)
    at PackageManager.t.exports.PackageManager.uninstall
(C:\Users\nsh\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:899547)
    at PackageCard.uninstall
(C:\Users\nsh\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2935250)
    at HTMLButtonElement.uninstallButtonClickHandler
(C:\Users\nsh\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:2920664)
deactivate @ VM22 <embedded>:11
2internal/process/warning.js:18 (node:166564) Warning: Use Cipheriv for
counter mode of aes-256-ctr
writeOut @ internal/process/warning.js:18

------

>

**Comment by cschindl** [comment]
The installation of 2 other plugins fails according to protocol (atom-ftp-editor, multiple-remote-ftp). Please remove these plugins or install GIT for windows on your PC to complete the installation. 

Do you have debug mode enabled? There are no entries in the log? And I still need answers to my questions ;)

**Comment by nagadas** [comment]
I will give you the information and I would like to test it to see if it is
available.


Host: ftp.shoplic.kr
Port: 21
Protocol: FTP - File Transfer Protocol
Encryption: Use explicit FTP over TLS (use explic FTP over TLS if available)
User: AN1ITRVX5EAPB4S6
Password: CtiSG650E9yh3LgRH2Xx

>

**Comment by cschindl** [comment]
The problem is that you are using FTPS, which is currently not supported by the plugin. Please use FTP or SFTP to connect.

**Comment by nagadas** [comment]
Okay.

I should contact the hosting company.

Thank you very much for your help.

2019년 4월 2일 (화) 오후 5:08, Carsten Schindler <notifications@github.com>님이 작성:
