### ISSUE TITLE
Cannot access ftp-remote-edit

### ISSUE THREAD

**Issue by kwameagboyi9** [h3imdall/ftp-remote-edit#278]
It used to ask me for a one time password but now its denying me access saying there are too many 
![Image 4-2-19 at 1 03 PM](https://user-images.githubusercontent.com/48325132/55421698-d66cbc00-5547-11e9-8d72-49daa428ab07.jpg)

**Comment by cschindl** [comment]
Hi @kwameagboyi9,

the error message will be thrown from your (S)FTP server. The master password will only be used once to decrypt the server list. Close connections by collapsing the server list or contact your server administrator. FTP-Remote-Edit uses only one open connection for each server.

**Comment by cschindl** [comment]
Hi @kwameagboyi9,

Did my answer help you so I could close the ticket?
