### ISSUE TITLE
[Feature Request] tab order/index on "Edit Servers"

### ISSUE THREAD

**Issue by joaopedroraldi** [h3imdall/ftp-remote-edit#279]
It would be very usefull to implement that.
I create around 4 servers a day and have to click each field to paste is a waste of time.
I have opened configuration-view.js but i don't have the knowledge to apply this configuration.

The order, in order witch is showing, should be this:
nameLabel = 0
hostLabel = 1
portLabel = 2
protocolSelect = 3
logonTypeSelect = 4
userLabel = 5
passwordLabel = 6
remoteLabel = 7
saveButton = 8
closeButton = 9

Thank you for your attention.
I would like to help in this code.

**Comment by cschindl** [comment]
Hi @joaopedroraldi ,

yes, switching between the input fields with tab would be very helpful. We use the TextEditorView for the input fields. This atom component does not contain a handler for the tab key although the community has wanted it for some time. So if you want to help, you should add a handler or see if you can work with HTML input fields in the meantime.

**Comment by cschindl** [comment]
Changes are now included in the new release ([0.16.0](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.16.0)).
