### ISSUE TITLE
`Edit Servers` button and message always appear

### ISSUE THREAD

**Issue by kamihicouki** [h3imdall/ftp-remote-edit#280]
If no host is registered, it behaves like the title above.

However, even when using the [URI handler] (https://github.com/h3imdall/ftp-remote-edit#uri-handler) function, `You can edit the servers from the Settings View width ftp-remote-edit : edit-servers` continues to be displayed.

And this can not be clicked or touched with the mouse cursor, it only accepts keyboard operations.

Thank you.

**Comment by wacki4** [comment]
As i understand - You are having this issue when there is no server in config?

**Comment by cschindl** [comment]
Changes are now included in the new release ([0.15.1](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.15.1)).
