### ISSUE TITLE
Can't duplicate files since 0.15.0

### ISSUE THREAD

**Issue by mooseling** [h3imdall/ftp-remote-edit#282]
"duplicate" file from context menu now doesn't work. Red error message appears: 

Ftp-Remote-Edit
No such file

Transfer log shows an error for latest transfer, which is downloading the new file. (Direction is "<--", status is "Error", progress is blank)

Copying and pasting files still works.

**Comment by cschindl** [comment]
Changes are now included in the new release ([0.15.2](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.15.2)).
