### ISSUE TITLE
[Feature Request] Select between single-click and double-click trigger

### ISSUE THREAD

**Issue by jar812k6** [h3imdall/ftp-remote-edit#289]
After using the new download system to download directories daily, I feel it would be useful if there was a setting to decide if a single-click or double-click event should be used in the plugin. The current single-click trigger just feels clunky since the download/upload version was released.

For example when I download a folder, I first left-click it to highlight the folder and then right-click to select the download option, which as well expands the folder structure. That functionality just feels out of place now as the folder shouldn't be forced to expand just for a download. 

As well if I accidentally double-click a folder, it will quickly open/close and 50% of the time hang with a loading symbol that requires Atom to be fully restarted in order to use that server again.

**Comment by wacki4** [comment]
Why do You first left click on folder? Clicking it directly with right click highlights it and allow to download correctly, without opening tree.

**Comment by jar812k6** [comment]
Hi wacki4, 

Not sure why you requested me to ask here just to provide that response rather than directly in the email where we have been communicating for months, but it's just industry standard to left click to select then right click to take action. 

I have tried your method and while it does indeed work, it still feels very unnatural and clunky. Especially if you right-click the wrong folder and need to re-right-click. 

At this point, I believe I will just hire a dev off Upwork or etc to make personal changes, rather than suggesting a new feature to the core plugin.

**Comment by wacki4** [comment]
@jar812k6 don't be upset, I didn't had time to verify it, and also i know that i'm not a maker of this plugin, so such change could not be accepted by @cschindl . After You post it here, i had a moment for verify Your need, so I've tested what You write, and give You feedback for this feature, as natural programmer, or like we wrote it down in previous messages ;) Please, do not be angry or dissapointed.

Why do You think that this is unnatural or clunky? The same way it works even in windows explorer, or other apps or system which allow file exploring. I've just now checked and also in fillezilla it works the same way.

**Comment by jar812k6** [comment]
Hello wacki4, 

I can confirm I am not upset or angry in any way. However, I am a bit disappointed as the reason I reached out to you with this request was exactly like the download/upload integration requests, I was willing to donate again via Paypal to help offset your time invested for the work involved. Rather than have me waste time making this post and then waiting numerous days of downtime, you could have simply provided your response directly to the email and I would have already had my requested changes completed and in-use. 

The left-click to select then right-click to trigger an action may just be a habit I have developed over the last 30 years rather than industry standards. However, literally every other developer I have ever worked hands-on with had the same exact flow so I guess I never knew any different until now. 

In regards to your named examples, neither windows explorer nor filezilla will expand folders on a left-click., the Left-click simply selects whatever is hovered over. 

After further review, it appears ftp-remote-edit is simply following Atoms footsteps as the core software operates the same way and expands on single left-clicks. I installed the "atom-tree-view-dblclick" package awhile back so I had not noticed that functionality was present in the core. Based on that aspect, I don't believe anything needs changed in ftp-remote-edit and my request is simply a personal optimization.

**Comment by cschindl** [comment]
Hi @jar812k6,

please excuse the late reply. This project is developed exclusively in my spare time. Submitting new feature requests is therefore never wasted time but it can happen that you don't get an answer right away. I am always trying to improve the plugin and implement new features that are useful to the general public. As you have already noticed, the plugin follows the footsteps of the core editor. Changing the click behaviour would irritate many users as they would like to be very close to the atom editor.
