### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by Astuceman** [h3imdall/ftp-remote-edit#29]
Hi 

I wanted to know if I can reset everything 
The first time, I have enter the wrong password, and I want to redo everything from the ground

(ps : your package is the best for editing file from server, tried several out there)

**Comment by cschindl** [comment]
Hi @Astuceman, 

to reset everything, you can delete the values in the settings.

1. Open the atom settings (File->Settings).
2. Select Packages.
3. Locate the "FTP Remote Edit" package in the list of installed packages.
4. Click "Settings".
5. Empty the fields "Encrypted Connection Configuration" and "Encrypted Password".
6. Reboot atom.

To change only the password and to keep the settings, you can also run command "ftp-remote-edit:change-password".

**Comment by Astuceman** [comment]
Thanks
