### ISSUE TITLE
Import from filezilla - Remote dir doesn't work right

### ISSUE THREAD

**Issue by Olli** [h3imdall/ftp-remote-edit#292]
The <RemoteDir> parameters of sitemanager.xml are not imported correctly.
<RemoteDir> contains values such 
```
1 0 6 htdocs 23 mydirectory
```
This should in ftp-remote-edit /htdocs/mydirectory

**Comment by cschindl** [comment]
Fixed in release [0.16.1](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.16.1). Please check if everything works correctly now.
