### ISSUE TITLE
Handshake failed: no matching client -> server cipher

### ISSUE THREAD

**Issue by wynstep** [h3imdall/ftp-remote-edit#296]
Every time I try to connect to my server, I have this problem, could you please help me in solving?

Many thanks

**Comment by cschindl** [comment]
Hi @wynstep,

I think your server uses a less secure algorithm. (https://github.com/mscdex/ssh2/issues/417). Please enable debug mode and look at the protocol. Unfortunately, you cannot overwrite the algorithm in the configuration at the moment. Please check if you can adjust the server settings.
