### ISSUE TITLE
Getting "read ECONNRESET" error after trying to upload files to another device

### ISSUE THREAD

**Issue by Eryl2000** [h3imdall/ftp-remote-edit#298]
I tried to upload a directory to another device, and it was sucessful. I then tried to upload a 2nd folder, and nothing happened. After waiting several minutes (with nothing happening) I closed and reopened Atom. Now it says "read ECONNRESET" when I try to view the files. No matter if I reset both my laptop and the other device, turn on/off wifi, restart ssh on the other device, I haven't been able to connect, and keep getting this same error message. I'm connecting over sftp. This has happened before and the only fix I ever found was completely factory resetting the other device (which I do not want to do again obviously). Do you know how to fix this?

**Comment by cschindl** [comment]
Hi @Eryl2000,

the error seems to be due to your device because the connection cannot be established. Possibly a software or hardware is defect. I could not find this error on any local or hosted server. Which device is it?
