### ISSUE TITLE
Remote only displays a few folder instead of all

### ISSUE THREAD

**Issue by darox** [h3imdall/ftp-remote-edit#300]
I just set up ftp-remote-edit in Atom and I like it so far. However, for some reason, it only displays 3 remote folders instead of 24. 

INFO:
Atom version: 1.38.2 on Ubuntu Ubuntu 18.04.2 LTS
Remote: Ubuntu 18.04.2 LTS

**Comment by cschindl** [comment]
Hi @darox,

if you are using FTP, please enable the option "Tree View - Show Hidden Files" in the [package preferences](https://github.com/h3imdall/ftp-remote-edit#package-preferences). Furthermore no symlinks are displayed at the moment.

**Comment by cschindl** [comment]
@darox Can I close issue here?
