### ISSUE TITLE
Improve loading time of package

### ISSUE THREAD

**Issue by cnrmck** [h3imdall/ftp-remote-edit#301]
Love love love this package. 

I have noticed that it adds significantly to startup time. 

![image](https://user-images.githubusercontent.com/22061955/60683592-c372cc00-9e55-11e9-9ae0-6d378d402006.png)

About 4.4 seconds, which is longer than any other packages I have installed and alone it accounts for 80.9% of my package loading time:
![image](https://user-images.githubusercontent.com/22061955/60683608-deddd700-9e55-11e9-8417-da10368bc797.png)

My current solution is to pause the package until I need it, then I enable it. Is this issue on the radar, or will enabling/disabling the package as needed be the recommended strategy to solve the problem?

**Comment by cschindl** [comment]
Hi @cnrmck,

your start time is extremely slow. Normally the package starts within 1 second. However, we can still optimize it a bit, so that it only needs about half the time. I'll take a closer look in the near future.

**Comment by cnrmck** [comment]
Ok got it. Thank you.

If need be I can run more tests to try to help get to the bottom of it

**Comment by cschindl** [comment]
Fixed in release [0.17.1](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.17.1). Please check if this could reduce your loading time.

**Comment by cnrmck** [comment]
Updated, yes much faster, thank you!
