### ISSUE TITLE
[Feature Request] Basic Window feature 

### ISSUE THREAD

**Issue by GovindArora** [h3imdall/ftp-remote-edit#302]
I have set up ftp-remote-edit in Atom and Its dream come true from me. before atom i was using [Other Editor Software ] which has very limited functionality. but it was only tool to edit file on ftp directly. I did not find any problem so far. only a small annoying thing is that i have  more then 2000 files in a folder on server and the remote tree view pane does not auto focus on item when i press a key like a file name starting with v when i press v button it does not auto scroll to items name starting with v .which is a default behavior of windows . i have  to scroll down the whole list.i hope this small feature will make it to next release update.

thanks

INFO:
Atom version: 1.38.2 on Win 7 / Win 10 X64
Remote: Centos shared server

**Comment by cschindl** [comment]
Hi @GovindArora,

the plugin works like the tree view of atom. A jump by key is therefore not supported. You can use the fuzzy finder (ctrl-alt-p) which indexes the server once. After that you can easily search for files and open them.
