### ISSUE TITLE
Errors with FTPS (SSL/TLS)

### ISSUE THREAD

**Issue by Aprania** [h3imdall/ftp-remote-edit#304]
Hello everyone.

I am very happy that FTPS (SSL / TLS) has been implemented on this plugin.

Unfortunately, I can't use it properly!
Let me explain better, when I save the file I have to load it several times because of an error and Atom send it empty on server.
When I upload instead, it sometimes works while others get this error:
"101057795:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:c:\projects\electron\vendor\node\deps\openssl\openssl\ssl\s3_pkt.c:365:".
Obviously the times it returns the error are more frequent than those that went well.

I use Windows 10 with frequent updates.
The problem occurs on multiple servers, using vsftpd managed by VestaCP with valid certificate issued by Let's Encrypt.
Using FileZilla on the same server, again with an encrypted connection using SSL / TLS, I do not receive any error and the files are loaded correctly.

Thanks for your attention, I hope that together we can solve this problem.
I await an answer and in the meantime I greet you.

**Comment by cschindl** [comment]
Hi @Aprania,

did I understand you correctly that the error happens randomly even if you try to upload the same file at short intervals (with opened connection)?

**Comment by Aprania** [comment]
Yes

**Comment by devorel** [comment]
i have same problem , i cant download any file from server with ssl mode !

**Comment by Aprania** [comment]
Now me too can't download any files either.

**Comment by cschindl** [comment]
Hi @Aprania, @devorel,

the download problem seems to be related to this #306. But its not the reported ftps error from @Aprania. Please don't mix the 2 issues.

**Comment by cschindl** [comment]
Hi @Aprania, @devorel,

now that the FTP library has been changed in 0.17.0, can you please check if the bug has been also fixed?

**Comment by devorel** [comment]
very good

‫בתאריך יום ג׳, 30 ביולי 2019 ב-11:18 מאת ‪Carsten Schindler‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by cschindl** [comment]
Hi @Aprania, @devorel,

so can I close the issue here?

**Comment by devorel** [comment]
yes

בתאריך יום ג׳, 30 ביולי 2019, 21:58, מאת Carsten Schindler ‏<
notifications@github.com>:
