### ISSUE TITLE
Files do not open

### ISSUE THREAD

**Issue by webd0120** [h3imdall/ftp-remote-edit#308]
I got this message when I connected debug mode. The folder opens but the file does not open. Somebody please help me. Thank you.

![20190725_105317](https://user-images.githubusercontent.com/26398634/61840001-b84a1380-aeca-11e9-9a6e-4b7e665b5580.png)

**Comment by cschindl** [comment]
Hi @webd0120,

the issue has already been reported in #306 and is still in work.
