### ISSUE TITLE
[Feature] focus on password field when ctrl + space

### ISSUE THREAD

**Issue by willmendil** [h3imdall/ftp-remote-edit#309]
Hi, 

When I open a new atom windows and hit ctrl + space I get the window prompting for the password, but the text field is not focused, basically, I have to use my mouse. Is it possible to automatically have the plug in focus on the text field. First world problem but would be more convenient. Thx

**Comment by cschindl** [comment]
Hi @willmendil,

that's strange. The field should already be focused. Which theme do you use? Maybe the focus is suppressed by another plugin?

**Comment by willmendil** [comment]
i'm using the one-dark theme. and i indeed have many plugins, i'll investigate if there's a conflict. might take a while
