### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by Astuceman** [h3imdall/ftp-remote-edit#31]
Hi

I found duplicate when you right clic on any file
(see the screenshot below)
![capture](https://user-images.githubusercontent.com/19632209/27010715-3830bf2c-4eab-11e7-9b32-b747ac45d034.PNG)

**Comment by cschindl** [comment]
Hi @Astuceman,
 
this is not a duplicate. There are 2 options:

1. "Edit Server": Here you can edit the selected server.
2. "Edit Servers": Here you can edit all servers.

**Comment by Astuceman** [comment]
Ok
