### ISSUE TITLE
Last Update Crashes Atom

### ISSUE THREAD

**Issue by defrinex** [h3imdall/ftp-remote-edit#310]
I don't know why but last update makes Atom crash when you connect to a server inside a folder.

Steps:
> open some folder
> connect to server inside that folder
> close connection
> wait 10-15 second
> crash

**Comment by defrinex** [comment]
Looks like its not related to folders but Simple FTP connection. No problem with SFTP but connecting to FTP makes it crash.

**Comment by cschindl** [comment]
Hi @defrinex,

I was able to reproduce the error. Apparently a crash occurs when a timeout is thrown, which is currently the case in the new atom version with FTP connections. (#306 ) Since I have to change the used FTP library, I will fix the bug as well.

**Comment by WiseEagle** [comment]
We very wait new update)

**Comment by Tabwire** [comment]
Same happens here, but while in a server. It just crashes randomly, even when I'm not using the editor at all.

**Comment by cschindl** [comment]
Fixed in release [0.16.4](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.16.4).
