### ISSUE TITLE
Drag out to download

### ISSUE THREAD

**Issue by Tabwire** [h3imdall/ftp-remote-edit#312]
Hi,

Really love this plugin, it offers everything and it's stable. I requested recently the file size to be added which you said you will add it to the future requests.

Can you also try to add drag out function for download?

Now, when you drag from finder/explorer to your FTP, it uploads, which is great! Can you also do when you drag from the Atom-tree to the desktop or any folder to download it there as well?

Thank you!

**Comment by cschindl** [comment]
Hi @Tabwire,

atom uses electron, which unfortunately does not support drag out in the current version. Therefore this cannot be implemented by the plugin.
