### ISSUE TITLE
550 The system cannot find the file specified.

### ISSUE THREAD

**Issue by zeydo** [h3imdall/ftp-remote-edit#313]
550 The system cannot find the file specified.
ftp-remote-edit version : 0.17.0

Ftp server windows / plesk panel

**Comment by cschindl** [comment]
Hi @zeydo,

to help you, I need to know what you were doing before the error occurred and a log of the debug protocol (see debug mode) would be great. To enable the debug mode please go to the atom settings and look for the package "ftp-remote-edit". Here you have to click on settings. Please activate the checkbox for debug mode. Then you can open the console via the menu "View" -> "Developer" -> "Toggle Developer Tools". The debug messages should be displayed in the console.

**Comment by zeydo** [comment]
Hello there,
I don't have any problems in version 16.4.
But in version 17.0 I just can't connect to the windows server ftp.
550 The system cannot find the file specified. He's warning.
I took a screenshot for you.
![image](https://user-images.githubusercontent.com/15876663/62219570-3d479800-b3b7-11e9-86da-c7ca26c8b068.png)

**Comment by cschindl** [comment]
What kind of FTP server is running there exactly? I just tried it with FTP enabled on a Windows Server 2012 and it worked fine here. Please take a screenshot of the FTP log. This is under the structure tree and can be extended. 

![image](https://user-images.githubusercontent.com/28109094/62222245-564e4a00-b3b3-11e9-95d6-da90b36fbb60.png)

**Comment by zeydo** [comment]
![image](https://user-images.githubusercontent.com/15876663/62271189-ade6c700-b440-11e9-83eb-f8f65f36363e.png)

**Comment by cschindl** [comment]
Please deactivate the option "Show Hidden Files" in the plugin settings. This will lead to an error. In the new version I will have a closer look at this issue.

**Comment by zeydo** [comment]
Tank you @cschindl

**Comment by cschindl** [comment]
Fixed in release [0.17.1](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.17.1).
