### ISSUE TITLE
Default panel width

### ISSUE THREAD

**Issue by p1x44r** [h3imdall/ftp-remote-edit#314]
Hello,

Every time I open atom I end up resizing the remote FTP panel as it's too narrow to fit the file tree for my projects.

I noticed there are several other extensions offering to specify default panel width upon startup and was wondering if something similar can be implemented here as well.

Thanks in advance!

**Comment by cschindl** [comment]
Hi @p1x44r,

it is possible to save the last state and load it when reopening Atom. This way the last width can be restored. Would that be a conceivable alternative?

**Comment by p1x44r** [comment]
Hi @cschindl ,

Thank you for your response.

Correct me if I'm wrong, but doesn't one need to have a project in order to restore the last state? I am using Atom without creating any projects. Please let me know if there's a way for me to restore the state without having to create a project for every codebase a work with (there are dozens).

**Comment by cschindl** [comment]
Hi @p1x44r,

I checked, and you're right. The status is saved and restored to the project. Can you tell me a plugin that restores a configurable default panel width on opening? Then I can have a look how they solved it. I've only seen plugins that use atom's project settings so far.

**Comment by p1x44r** [comment]
Hi @cschindl ,

Here's one package that has default panel width as as setting: symbols-tree-view

I'm not sure if their panel implementation is the same, but changing the setting definitely  has an effect.

Thank you very much for taking your time to investigate this further!

**Comment by cschindl** [comment]
Hi @p1x44r,

unfortunately the plugin "symbols-tree-view" still uses panels. These have been replaced by the docks since atom version 1.17.0. Docks have the advantage that they can be changed by tabs and can be moved by the user. Our plugin, like most other plugins, already uses docks. However, it seems that atom takes care of the placement and the width itself. Do you have any other plugins I can look at?

**Comment by p1x44r** [comment]
Hi @cschindl ,

I did some legwork for you and found out that several other plugins that let one resize the panel upon Atom's startup also use panels. 

I can live with things being as they are. It was always in a "nice to have" category and isn't anything pressing. If at some later point in time things change and option becomes availble, please remember our conversation. :)

Thank you very much for your time!
