### ISSUE TITLE
Cannot parse privateKey: PPK private key integrity check failed

### ISSUE THREAD

**Issue by sebafurfaro** [h3imdall/ftp-remote-edit#316]
Hi, I have a problem with the Ftp-Remote-Edit package. Until the last update, I could connect with my PEM key correctly. But after the last update I get this error:
"Cannot parse privateKey: PPK private key integrity check failed"
Any suggestions, since my PEM key is correct and is compatible with ssh2 library?
Thanks

**Comment by cschindl** [comment]
Hi @sebafurfaro,

the SFTP or SSH programming logic was not changed by the last plugin update. The error must therefore be caused by the atom update or a change to the operating system or server.
