### ISSUE TITLE
Opening takes quite long

### ISSUE THREAD

**Issue by pixeldesignstudio** [h3imdall/ftp-remote-edit#317]
While opening a (small) file it takes around 30-60 seconds to open. 
The process wheel is animated and nothing happens until it opens.

**Comment by cschindl** [comment]
H @pixeldesignstudio,

to help you, I'd need to know if you connects via ftp or sftp and a log of the debug protocol (see debug mode) would be great. To enable the debug mode please go to the atom settings and look for the package "ftp-remote-edit". Here you have to click on settings. Please activate the checkbox for debug mode. Then you can open the console via the menu "View" -> "Developer" -> "Toggle Developer Tools". The debug messages should be displayed in the console.

Are you already using the latest version of this plugin?

**Comment by pixeldesignstudio** [comment]
Since the last update, it works fine now.
