### ISSUE TITLE
Mouse wheel scrolling

### ISSUE THREAD

**Issue by Sa1ch** [h3imdall/ftp-remote-edit#318]
Hello!
Panel with a list of sites on the left, loses focus when the file is open. And if the cursor is above the panel, it stops responding to the mouse wheel.

**Comment by cschindl** [comment]
Hi @Sa1ch,

that's weird. Unfortunately, I cannot reproduce it. When opening a file, the focus is placed on the file. Scrolling by keyboard is on the file but scrolling by mouse over the list should work normally. Is this possibly suppressed by another installed plugin?

**Comment by Sa1ch** [comment]
I do not know. how can this be checked?

**Comment by cschindl** [comment]
Hi @Sa1ch,

I don't know how many plugins you've activated. The easiest way to test it is to deactivate all plugins. If the error is fixed, you can activate each plugin one after the other until the error occurs.

**Comment by cschindl** [comment]
Since nothing new has come up on this, I close the ticket.
