### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by Astuceman** [h3imdall/ftp-remote-edit#32]
Hi

When I try to rename any file it's show a prompt with "no such file"
I tried to change `index.css` by `indexx.css`
(see the screenshot below)
![capture2](https://user-images.githubusercontent.com/19632209/27011493-e6118bd8-4ebc-11e7-8ec4-79a5479ecd4d.PNG)

**Comment by jordan-webdev** [comment]
I get the same issue. It gives the same issue if I try to add a directory, as well.

**Comment by cschindl** [comment]
I can not reproduce the error. Please activate the debug mode and write the output here purely. The debug mode can be activated as follows:

1. Open the atom "config" (File -> config)
2. Search for "ftp-remote-edit"
3. Add the line as a sub-dot: "debug: true"

The config should then look something like this:

"Ftp-remote-edit":
     Config: "54baad1 ....."
     Password: "78b2 ... 622"
     Debug: true

4. Save and restart the Atom editor
5. Toogle Delevoper Tools (Ctrl + Shift + i) and open the "Console"

Then please try to rename a file or create an directory and post the output here.

**Comment by Phoax** [comment]
For renaming "ok2.php" to "ok3.php", in the console I have:
`sftp:rename /home/phoax/www/test/ok2.php /home/phoax/home/phoax/www/test/ok3.php`
Maybe it is the double /home/phoax/home/phoax in the destination filepath.

For creating a "test2" folder:
```
connector:createDirectoryStructure [
"/home",
"/home/phoax",
"/home/phoax/www",
"/home/phoax/www/test2"]
0: "/home/factory"
1: "/home/phoax/www"
2: "/home/phoax/www/test2"length: 
3__proto__: Array[0]
```

**Comment by cschindl** [comment]
I could find the error when renaming the file. You were right. The initial directory was added twice in the path.

The log when creating a folder looks as far as ok. Was the creation successful? If not please post the whole log so we can check the commands.

**Comment by Phoax** [comment]
Great for the renaming.

Unfortunately it does not solve the folder creation problem. It seems that the path is lost when calling Client.list

If I add some console.log in connector.js l.161, I never see my "hello1"
```
// Walk recursive through directory tree and create non existing directories
    console.log('hello0');
    return Client.list(directory)
      .then((list) => {
        console.log('hello1');
```

And in sftp.js, remotePath is empty
```
list(remotePath) {
    const self = this;
    if (self.debug) console.log('sftp:list', remotePath);
```

![atomdebug](https://user-images.githubusercontent.com/7249024/27585706-9cdda694-5b3d-11e7-9bb4-db6660586f94.png)

**Comment by Phoax** [comment]
In connector.js, on l. 159, console.log(directory) seems empty
```
let path = remotePaths.shift();
    let directory = path.split('/');
    directory.pop();
    directory = directory.join('/');
    console.log(directory)
```

**Comment by cschindl** [comment]
Please add the following in connectors.js at line 160 and try again:
if(!directory)directory = '/';

Here is an example off an successfully creating process of the directory "a" in the initial directory "public_html".

![log](https://user-images.githubusercontent.com/28109094/27589872-332589a0-5b4d-11e7-97bd-5f431e012bcb.jpg)

You can see that die connector list the parent directory of "/" to see if the directory "public_html" exists. In that case the directory already exists, so the connector try the next child directory. So he try to list the "/public_html" directory to find the "a" directory. This directory doesnt exists so it will be created by the sftp command mkdir "/public_html/a".

Can you see this behavior in your case? I miss the mkdir command in your logs?

**Comment by Phoax** [comment]
Nice! It works. I can create/rename folders
Thank you, nice plugin

**Comment by Phoax** [comment]
When I set an `Initial Directory`, like `/home/phoax`, and I want to rename a file in it, it fails, "No such file"

For example, renaming `/home/phoax/hello.txt` to  `/home/phoax/hello.txt2` fail
But if I remove the Initial Directory in the Dialog box, and rename `hello.txt` to `hello2.txt`, it works.
