### ISSUE TITLE
Upload from Project

### ISSUE THREAD

**Issue by Goten87** [h3imdall/ftp-remote-edit#327]
i have a project and i like this plugin a lot but there is no way to upload to the server from projects
im new and still finding my way so if its in already sorry but if its not can you make it so we can also upload files from our projects to a server

**Comment by cschindl** [comment]
Hi @Goten87,

projects are displayed by the atom plugin "treeview". Unfortunately this plugin does not offer the possibility to infiltrate a functions from an external plugin like ours. An option to upload project files is unfortunately not possible. At the moment you can only drag and drop files and folders from the file system of your OS into our plugin or right click on a folder and select upload.
