### ISSUE TITLE
Unable to load server files ever since updating to 0.17.2

### ISSUE THREAD

**Issue by NoExtraSauce** [h3imdall/ftp-remote-edit#328]
![image](https://user-images.githubusercontent.com/54363882/63437689-e3207c80-c422-11e9-9399-ad277f9f6ce5.png)

**Comment by cschindl** [comment]
Hi @NoExtraSauce,

to help you, I'd need to know if you connects via ftp or sftp and a log of the debug protocol (see debug mode) would be great. To enable the debug mode please go to the atom settings and look for the package "ftp-remote-edit". Here you have to click on settings. Please activate the checkbox for debug mode. Then you can open the console via the menu "View" -> "Developer" -> "Toggle Developer Tools". The debug messages should be displayed in the console.

**Comment by NoExtraSauce** [comment]
﻿
tree-view.js:277 connector:listDirectory /
tree-view.js:278 connector:connect
tree-view.js:278 ftp:connect
tree-view.js:278 ftp:debug: Connected to (I have removed this)
tree-view.js:278 ftp:debug: Login security: No encryption
tree-view.js:278 ftp:connect:ready
tree-view.js:278 ftp:list
tree-view.js:278 connector:disconnect
tree-view.js:278 connector:disconnect
tree-view.js:278 connector:abortAll
tree-view.js:278 connector:connect
tree-view.js:278 ftp:abort
tree-view.js:278 ftp:end

**Comment by cschindl** [comment]
Hi @NoExtraSauce 

what kind of FTP server is running there exactly? Please take a screenshot of the FTP log. This is under the structure tree and can be extended.

![62222245-564e4a00-b3b3-11e9-95d6-da90b36fbb60](https://user-images.githubusercontent.com/28109094/63637783-32fc7f00-c681-11e9-8065-d439252d9a7c.png)

**Comment by NoExtraSauce** [comment]
Hi Sorry for the delayed response, please see below:
![image](https://user-images.githubusercontent.com/54363882/63800413-f4c3c180-c905-11e9-875b-abd0e4a2d007.png)

**Comment by cschindl** [comment]
Fixed in release [0.17.4](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.17.4). Please check if the adjustments to the FTP library (https://github.com/patrickjuchli/basic-ftp/issues/91) have now fixed the error.
