### ISSUE TITLE
Add option to display dialog to confirm drag & drop action

### ISSUE THREAD

**Issue by mooseling** [h3imdall/ftp-remote-edit#334]
I use ftp-remote-edit all day every day, and I have on occasion accidentally dragged a folder into another in the tree view. Typically, my intention was to open a folder, but buggy mouse functionality caused me to drag it instead. Since I'm working on a web root, the effects could be pretty bad, and it can be difficult to know where the folder has been moved to, or notice that it has been moved at all. Would be nice to be able to disable this.

**Comment by cschindl** [comment]
Hi @mooseling,

I think it would make more sense than a general switch off/on to create an option that asks if you want to do this before copying/moving. If the option is then disabled, the process is simply performed as it is now. If the option is activated, you will be asked beforehand. Would that be enough for you?

**Comment by mooseling** [comment]
That would be brilliant!

**Comment by cschindl** [comment]
Changes are now included in the new release ([0.18.0](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.18.0)).
