### ISSUE TITLE
Failed to upload data stream to remote server

### ISSUE THREAD

**Issue by t0msk** [h3imdall/ftp-remote-edit#335]
Hello,

I use ftp-remote-edit for long time and I never had any problem with it, but today it suddenly stopped working, on every file what I want to upload I am getting `Failed to upload data stream to /remote_path/remote_file.mdl: Failure`, and it uploads empty file, so it deletes all code in files, it was always working, but today it stopped, and I don't know what to do, I tried:

- update package to newest version
- delete contents in `/tmp/` directory
- restart Atom
- restart computer

but nothing helped.

I use KDE neon 5.16 as Linux distro.

**Comment by t0msk** [comment]
I fixed it, problem was that my disk on the server was full.

**Comment by cschindl** [comment]
Good to hear you were able to solve the problem. Then this issue can be closed.
