### ISSUE TITLE
Spins on opening files/directory after a network disconnect

### ISSUE THREAD

**Issue by rajeshvig** [h3imdall/ftp-remote-edit#339]
if network breaks for few minutes, it keeps on spinning to open file/directory before throwing error. There is no option to reconnect. Workaround to edit/save server helps sometimes. 

using Atom on MacOS mojave

**Comment by cschindl** [comment]
Hi @rajeshvig ,

the issue has already been reported in #290. However, it seems to be a MacOS problem which is very difficult to reproduce. You may be able to help reproduce the error.
