### ISSUE TITLE
Uncaught TypeError: Cannot read property 'domNode' of undefined

### ISSUE THREAD

**Issue by ChrisRackauckas** [h3imdall/ftp-remote-edit#344]
It just randomly pops up.

**Comment by cschindl** [comment]
Hi @ChrisRackauckas,

to help you, we'd have to be able to reproduce the error. It is therefore necessary to know exactly what you did before the error occurred.

**Comment by ChrisRackauckas** [comment]
If I use Atom/Juno long enough (I don't know, a few hours?), then this error randomly starts popping up, and I reset Atom to fix it. @pfitzseb have you seen this?

**Comment by pfitzseb** [comment]
[Yup](https://github.com/JunoLab/atom-ink/issues/224). Not sure why that's reported by this package though, should be completely unrelated.

**Comment by ChrisRackauckas** [comment]
Awesome.

**Comment by pfitzseb** [comment]
Should be fixed with ink 0.11.1, btw.
