### ISSUE TITLE
handshake failed no matching key exchange algorithm

### ISSUE THREAD

**Issue by yakir12** [h3imdall/ftp-remote-edit#345]
Hi!
The client is Ubuntu 18.04.1, the server is Debian 11, I can ssh fine to the server with the same settings specified in the ftp-remote-edit server settings, I can sftp and get and put files, but still get a `handshake failed no matching key exchange algorithm` error whenever I test the server via the ftp-remote-edit server settings.
Any clue what I should try?

Thanks in advance!

P.S. 
I couldn't find any documentation.

**Comment by cschindl** [comment]
Hi @yakir12,

the error message is thrown by the sftp library if no matching authentication method can be found. We use the [ssh2-sftp-client ](https://github.com/theophilusx/ssh2-sftp-client)library. Have you checked here if other users might have the same problem?

**Comment by yakir12** [comment]
Sorry, so is `ssh2-sftp-client` a dependency for the client, server, or both? I installed it on both the client and server but that did not resolve the issue. Or am I supposed to do something more than just 
``` 
(sudo) npm install ssh2-sftp-client
```

> Have you checked here if other users might have the same problem?

While there are a number of similar issues, I couldn't find one that worked for me. Apologies if I missed it (and a typo I just found in my original post).

**Comment by yakir12** [comment]
The problem was that I had specified a specific `KexAlgorithms` in my `sshd_config`. The person who solved this was Joshua Gentry on [this](https://discourse.julialang.org/t/ssh2-sftp-client-in-ftp-remote-edit-juno-in-atom/29653) Discourse topic.
