### ISSUE TITLE
Hop through an ssh login node

### ISSUE THREAD

**Issue by michel2323** [h3imdall/ftp-remote-edit#346]
Hi,

I want to hop through a login node to get on a machine that is not directly on the internet. 

`ssh -A -t loginserver ssh -A workstation`

Easiest way would be to allow a custom ssh command.

Thank you.

Edit: Nevermind. The actual easiest I guess would be to use the Socks API of `ssh2-sftp-client`. Unfortunately I'm a javascript noob.

**Comment by cschindl** [comment]
Hi @michel2323,

could it be that your request is the same as this request https://github.com/h3imdall/ftp-remote-edit/issues/264 or this https://github.com/h3imdall/ftp-remote-edit/issues/240?
