### ISSUE TITLE
Spinning icon and foldername

### ISSUE THREAD

**Issue by janstieler** [h3imdall/ftp-remote-edit#347]
Hi,
I use Atom 1.42 and Remote-FTP 0.17.4.
I have the problem that on open a folder the whole name and icon is spinning.
As I see the `packages/build/styles/build.less` file have a spin-class which is affecting the surrounding `span` and not only the `spin:before` from your `ftp-remote-edit/styles/ftp-remote-edit.less`. I don't know if the build.less comes from Atom or another package.

Cheers

**Comment by cschindl** [comment]
Hi @janstieler,

styles are often overwritten by themes. To help them I need the information which theme you are currently using and if the error also occurs with the standard themes.

**Comment by janstieler** [comment]
Hi @cschindl,
I use the one light ui theme. 
I think the problems comes from another plugin if it is not present on a new Atom installation.
But how should I find this plugin?

Cheers

**Comment by cschindl** [comment]
Hi @janstieler,

you can use atom's developer tools (View->Developer->Toggle Developer Tools) to inspect the properties of each element. This will show you exactly which css is causing the effect. This way you can also find the plugin.

**Comment by janstieler** [comment]
Hi @cschindl,
there is only one package, file-icons affected. But the classes from this packages are not the problem.

/Users/Jan/.atom/packages/ftp-remote-edit/styles/ftp-remote-edit.less
This is your Less-File where you have declared `.spin::before {}` which should affected only the icon
but in the two files:
/Users/Jan/.atom/packages/build/styles/build.less
/Users/Jan/.atom/packages/build/styles/animations.less
there is declared `.spin {}`which rotate the whole name and the icon as one.
These two less-files are atom native files and come not from a additional package. 

I have added also a gif that you can see what my problem is:
![Bildschirmvideo aufnehmen 2019-10-29 um 22 30 57](https://user-images.githubusercontent.com/754880/67811594-6dc5cd80-fa9d-11e9-85bf-6c152b1232d9.gif)

So you should have also the problem, or?

Cheers

**Comment by cschindl** [comment]
Hi @janstieler,

with your help I was able to find the plugin that caused the error. (https://atom.io/packages/build) I will try to adjust the styles so that they don't conflict with the plugin anymore.

**Comment by cschindl** [comment]
Fixed in release [0.18.0](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.18.0)
