### ISSUE TITLE
Can't upload bigger folder. 

### ISSUE THREAD

**Issue by d3tr1tus** [h3imdall/ftp-remote-edit#348]
I can't upload bigger folder. After 30s say that. Error: Set timeout...
Can you give me advice how can i solve it?

Thanks

**Comment by cschindl** [comment]
Hi @d3tr1tus,

unfortunately, the upload is not optimized for larger files or data volumes. It should only be used for smaller files. The plugin is not a replacement for a real (S)FTP client. It should only simplify the editing of files on the remote server. Please use an (S)FTP client such as FileZilla to upload large amounts of data.
