### ISSUE TITLE
[Suggestion] Toggle ftp-remote-edit on startup

### ISSUE THREAD

**Issue by miles-collier** [h3imdall/ftp-remote-edit#35]
It would be nice if there was an optional setting that would prompt for your package password on Atom launch. I only use Atom with SFTP/FTP, figured this would be a nice QOL change

**Comment by cschindl** [comment]
We plan to change the plugin to support the Atom Editor's new design so that docks are used instead of panels. For this, the start must be changed anyway. Therefore, the chances are good that we implement the function.

**Comment by BWPanda** [comment]
In the meantime, you can add this to your Init Script:

`# Toggle ftp-remote-edit
atom.commands.dispatch(document.querySelector('atom-workspace'), 'ftp-remote-edit:toggle')`
(copied from: https://github.com/kuychaco/multirow-tabs/issues/5#issuecomment-216224463)
