### ISSUE TITLE
Temporarily Hide Servers From Tree List

### ISSUE THREAD

**Issue by wpcodeus** [h3imdall/ftp-remote-edit#351]
Hello, is there a way to temporarily hide a server from the tree list panel? I would still like to have that information saved for when working on that project again in the future, but want to limit the tree list view to only projects I am working on at the time to eliminate accidentally editing the wrong files in another server that has a similar structure.

If this is currently not a feature, it would be an awesome one!

**Comment by cschindl** [comment]
Hi @wpcodeus,

there is currently no option to hide. But you can create folders and move currently unused servers into them. Maybe this will help you already.
