### ISSUE TITLE
Passive / Active mode

### ISSUE THREAD

**Issue by ataofaichi** [h3imdall/ftp-remote-edit#356]
Where to swithc as my server allows only active mode

**Comment by cschindl** [comment]
Hi @ataofaichi,

unfortunately only the passive mode is supported at the moment. We use the library [basic-ftp](https://github.com/patrickjuchli/basic-ftp). This library currently only supports this mode. If the active mode is available, we can implement this. But you have to contact the owner of the library. Unfortunately we can't do anything about this at the moment.
