### ISSUE TITLE
Export serverlist?

### ISSUE THREAD

**Issue by janstieler** [h3imdall/ftp-remote-edit#357]
Hi,
is it possible to export all my servers as a list width password?
Not only a decrypted config string from the config.cson or is it possible to decrypt the string?

Cheers

**Comment by cschindl** [comment]
Hi @janstieler,

at the moment there is no possibility to export the list unencrypted. The data is encrypted by aes-256-ctr with your master password. So you could only decrypt the encrypted information yourself.

```javascript
const crypto = require('crypto');

password = 'ENTER PASS HERE';
test = 'COPY ENCRYPTED DATA HERE';

let decipher = crypto.createDecipher('aes-256-ctr', password);
let dec = decipher.update(text, 'hex', 'utf8');

console.log(dec);
```
