### ISSUE TITLE
Atom shutdown on macOS Catalina when create file/folder throught ftp-remote-edit

### ISSUE THREAD

**Issue by muzanaka** [h3imdall/ftp-remote-edit#358]
After update to Catalina atom sometimes go away when I create a file or folder.

**Comment by cschindl** [comment]
Hi @muzanaka,

unfortunately errors are difficult to solve and only if they are reproducible. It would therefore be good if you could show a way to reproduce the error. Then I will gladly take a look at this. Until then I close this ticket for now.
