### ISSUE TITLE
Visual Studio Code version

### ISSUE THREAD

**Issue by beysim** [h3imdall/ftp-remote-edit#359]
Hey,
first, thank you for your great work! This was my favorite extension when I was using the Atom editor.
Switched to Visual Studio Code and I really miss this extension. None of the other similar extensions available for the vscode are as good as yours.
Any plan to release a Visual Studio Code version of this great extension?

Thanks

**Comment by cschindl** [comment]
Hi @beysim,

thanks for using our plugin. Currently there is no version for Visual Studio Code planned. VSCode has its own API, which allows only limited access to the DOM. So a lot of customization would be necessary. Unfortunately I don't have the time for it at the moment.
