### ISSUE TITLE
Hide password in server settings

### ISSUE THREAD

**Issue by uwf-doc** [h3imdall/ftp-remote-edit#36]
This plugin is perfect, except I really wish it obscured the password on the server settings page. Even if there was a checkbox to hide/show the password field that would work.

**Comment by miles-collier** [comment]
I feel that it's not very needed, because to get to that setting you have to enter the master password. However wouldn't hurt, especially if you're streaming to people and don't want to show off passwords on accident.

**Comment by uwf-doc** [comment]
Yes, exactly. It's not the end of the world since you already need to enter your password to get to that screen, but if someone's looking over your shoulder they can see your login credentials. It's very insecure is all.

**Comment by cschindl** [comment]
Hi @uwf-doc ,

thanks for the hint. I made the changes and submitted a new pull request. You are right that the input of passwords should always be masked. This should improve security.

**Comment by uwf-doc** [comment]
@cschindl Great work! Passwords are now obscured and I can sleep peacefully at night. Thank you.
