### ISSUE TITLE
[Feature Request] 2 factor authentication

### ISSUE THREAD

**Issue by DerMatteo** [h3imdall/ftp-remote-edit#361]
Hello! Is it possible to add support for 2 factor authentication? It makes my server secure, but then i cant use atom... and thats not cool. Would be great if you could include this ;D

Thanks

**Comment by cschindl** [comment]
Hi @DerMatteo,

unfortunately this is currently not possible. We use the library [ssh2-sftp-client](https://github.com/theophilusx/ssh2-sftp-client) for SFTP connections. This library does not support 2 factor authentication. If this should be the case at some point, we can implement this here.
