### ISSUE TITLE
Files can't be deleted

### ISSUE THREAD

**Issue by SoraCent** [h3imdall/ftp-remote-edit#387]
Good Day,
I guess I found a bug.

Everytime if I try to delete a File with the "Del" button or with Rightclick and Delete nothing happends the file isn't getting deleted.
I always need to connect with Filezilla to delete the files.

Is this a Bug or something wrong in the settings ?

Thanks for reading.

**Comment by jordan-webdev** [comment]
This just started happening to me too recently. Any fix?

**Comment by Remling97** [comment]
Happend to me too, also i cant upload and replace files, like i get the popup if i want to overwrite the old file but nothing happends afterwards

**Comment by Arsavin** [comment]
I have the same problem as you guys.
That started to happen a few days ago @h3imdall .

**Comment by joecarl** [comment]
Same here!

**Comment by andrenalin282** [comment]
Same here...
Atom 1.52.0 x64
ftp-remote-edit 0.18.0

**Comment by funktionaer** [comment]
Same here...
Atom 1.52.0.
ftp-remote-edit 0.18.0
Can't delete files and can't upload and replace files as well

**Comment by Wolfilius** [comment]
Same for me
Atom 0.52 ftp-r-e 0.18

**Comment by michretz** [comment]
same here
Atom 1.52.0
ftp-remote-edit 0.18.0

**Comment by lordpt** [comment]
Here the same problem 
Atom 1.52.0 x64
ftp-remote-edit 0.18.0

**Comment by Pinceptor** [comment]
this problem actual from athom v 1.52. Get the [athom 1.51](https://www.dropbox.com/s/zj0d3pix2y5u0wq/AtomSetup-x64.exe?dl=0), pres "**ctrl+,**" and disable the item "_Automatically Update_" until the problem is resolved

**Comment by chrion02** [comment]
Or get atom from the official repo: https://github.com/atom/atom/releases/tag/v1.51.0

**Comment by cschindl** [comment]
Fixed in [0.18.1](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.18.1). Thanks for the hint. Please update.
