### ISSUE TITLE
Two connection errors

### ISSUE THREAD

**Issue by jordan-webdev** [h3imdall/ftp-remote-edit#39]
I really like the design of this and want to use it, but on some servers I get "Timed out while waiting for handshake" error. The strange part is that I was able to connect to this server before, but it was giving me a permissions error when trying to connect to the home directory, where public_html is. I'm able to connect to the server just fine using the same credentials on atom-commander and Notepad++ FTP

**Comment by miles-collier** [comment]
This happens to SFTP, FTP, or both?

**Comment by jordan-webdev** [comment]
SFTP for sure, but I think both.

This works for another site of mine, though, but it's using a different hosting provider. I contacted my hosting provider and they did not see any issues on their end.

**Comment by jordan-webdev** [comment]
Hey, sorry, the reason for the handshake issue was because my hosting provider blocked my IP.

However, I'm still getting the "permission denied" error while trying to access the home directory.

**Comment by jordan-webdev** [comment]
Hey guys, apologies, the error was on my end. The directory I was trying to access was owned by root. I talked to my hosting provider and they changed it to use jail cell, which solved the problem! Great package! Very happy to have found it.
