### ISSUE TITLE
Files not getting uploaded

### ISSUE THREAD

**Issue by chrion02** [h3imdall/ftp-remote-edit#394]
I'm getting the green popup response when saving, as if the file is successfully uploaded to the ftp, but it's not.

I have been using this package for daily development for more than a year now and have never had this issue. I have not changed anything in my hosting or dev setup.

**Comment by chrion02** [comment]
Issue is due to atom 1.52 update

**Comment by cschindl** [comment]
Fixed in [0.18.1](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.18.1). Thanks for the hint. Please update.
