### ISSUE TITLE
Loading spinner keeps rotating forever

### ISSUE THREAD

**Issue by kirschkern** [h3imdall/ftp-remote-edit#4]
When opening a file from a server, the spinning symbol indicating the loading of a file, keeps rotating forever. Even after closing the file again, the symbol still rotates. This is irritating - especially when multiple files are opened.

**Comment by sadikyalcin** [comment]
+1

Toggling the parent folder helps.

**Comment by h3imdall** [comment]
The issue was solved in version 0.8.0.
