### ISSUE TITLE
Downloading code issue

### ISSUE THREAD

**Issue by edwinsoto88** [h3imdall/ftp-remote-edit#414]
When I try to download code from the sftp server, the code that I try to download doesn't show up on my personal machine. And when I try downloading code using sftp, the green box that lets you know you downloaded stuff, doesn't pop up.

**Comment by bear30** [comment]
Hello,my downloads also crashs. I can choose the client directory on my ubuntu 20.04 and after that nothing happens. It works perfectly until last week. Greetings from germany

**Comment by moritzgubler** [comment]
I have the same issue. Uploading files also does not work. It worked perfectly until last week or so.

**Comment by Koriganp** [comment]
unable to download remote files.

**Comment by MichaelRThompson** [comment]
Same, no problems until earlier this week.

**Comment by existenzmaximum** [comment]
Same here, no upload, no download happening ...

**Comment by cschindl** [comment]
Hi,

to help you, I'd need to know if you connects via ftp or sftp and a log of the debug protocol (see debug mode) would be great. To enable the debug mode please go to the atom settings and look for the package "ftp-remote-edit". Here you have to click on settings. Please activate the checkbox for debug mode. Then you can open the console via the menu "View" -> "Developer" -> "Toggle Developer Tools". The debug messages should be displayed in the console.  I also need the information which os you are using. Furthermore, please execute the command "apm -v" in the console and write the versions here.

**Comment by MichaelRThompson** [comment]
- SFTP
- Windows

> apm -v
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.56.0
python 3.8.3
git 2.30.0.windows.2
visual studio

I have no debug messages when I try to download or upload anything., just nothing happens. Opening a file that already exists on the remote works just fine, and I get a handful of SFTP debug messages that all look normal.

**Comment by moritzgubler** [comment]
- SFTB
- Ubuntu
- With the debug mode enabled I get no error message. Nothing happens and no file is downloaded.
- Output of apm -v:
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.56.0
python 3.7.3
git 2.25.1

**Comment by cschindl** [comment]
Fixed in [0.18.2](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.18.2). Please update.

**Comment by existenzmaximum** [comment]
Works like a charm again :) Thank you very much!

**Comment by MichaelRThompson** [comment]
Very nice, looks good.  Thank you for the quick turnaround on this.

**Comment by bear30** [comment]
Thank you! Now it work's perfectly!
