### ISSUE TITLE
Upload and Download still not working

### ISSUE THREAD

**Issue by ZhiKosta** [h3imdall/ftp-remote-edit#416]
https://github.com/h3imdall/ftp-remote-edit/commit/a61fa4919d6d408b893cbca40a310835bac8b2c8

These do not resolve the issue in the new version.

**Comment by janstieler** [comment]
Hi,
I have also problems to download files.
If I start it i got a window where to select my downloadfolder and than nothing happens.

**Comment by alexey-m-pavlov** [comment]
Hello! 

+1 here: 

SFTP, Windows 

No error message when debug is enabled.

Output of apm -v:
```
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.56.0
python
git
visual studio
```

**Comment by cschindl** [comment]
Hi,

the issue has already been reported in #414
