### ISSUE TITLE
Can create files, but can't create folders: "No such file"

### ISSUE THREAD

**Issue by Phoax** [h3imdall/ftp-remote-edit#42]
I use SFTP, I can create files, but I can't create folders. I have the _"No such file"_ error.
In #20 that "The problem about creation of folders is solved" but I still have this problem. Is there any way to solve this ?
I'm using Windows 10 and ftp-remote-edit 0.11.7

**Comment by Phoax** [comment]
It is the same error when renaming a file.

**Comment by cschindl** [comment]
@Phoax  The error has already been reported in issue #32 and a solution is being worked on. Please use issue #32.
