### ISSUE TITLE
FTP with TLS/SSL encryption

### ISSUE THREAD

**Issue by joecarl** [h3imdall/ftp-remote-edit#45]
Please enable FTPS, some servers won't let SFTP connections, and allowing plain FTP connections is quite insecure. FTPS would be a big step!

**Comment by syrof** [comment]
Any chance for FTPS?

**Comment by Aprania** [comment]
Please insert this important feature! :-(

**Comment by cschindl** [comment]
Changes are now included in the new release ([0.16.3](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.16.3)).

**Comment by Aprania** [comment]
Wow! Perfect, grat job! I can make a donation?

**Comment by cschindl** [comment]
We are grateful for any donation. You will find a link to our Paypal account in the section "[I'd like to support this project](https://github.com/h3imdall/ftp-remote-edit#id-like-to-support-this-project)". We would also be happy if you would rate this project with a star at atom and github.
