### ISSUE TITLE
Path to private keyfile not editable

### ISSUE THREAD

**Issue by swiftouch** [h3imdall/ftp-remote-edit#48]
The path to private keyfile box is not editable. 

Maybe I'm missing something, but I can't add anything in that field.

Thanks.

**Comment by maddick** [comment]
Same issue here

**Comment by cschindl** [comment]
Did you check the sftp checkbox?

**Comment by colexyz** [comment]
Having the same issue, with the SFTP checkbox toggled.

**Comment by swiftouch** [comment]
This is working for me now. I don't know if the plugin got updated or what changed to allow typing in that box. But it's working.

**Comment by tbezdeka** [comment]
This was also a problem for me right after installing `FTP-Remote-Edit` - restarting Atom fixed it.

**Comment by digikokki** [comment]
I am not able to write path even if I have check the checbox.
Atom 1.19.0

**Comment by cschindl** [comment]
Hi @digikokki,
 
I can not reproduce the error.  Can you give me some more step by step information?

**Comment by cschindl** [comment]
The error has been corrected 3edc5348617c351f984aadd90d01995c7b7027fe and the changes will be available in the next release.
