### ISSUE TITLE
Add option to download files

### ISSUE THREAD

**Issue by guerra08** [h3imdall/ftp-remote-edit#50]
The package is really good and solid. But, an option to download the files from the server would be very appreciated!

**Comment by jordan-webdev** [comment]
+1

Also, the ability to drag and drop files for upload, similar to Notepad++'s NppFTP plugin.

BTW thank you for acting on our requests! Renaming works for me now, and the ctrl + space shortcut is very convenient.

**Comment by cschindl** [comment]
Hi @guerra08,

the purpose of this plugin is that you can edit files directly without first downloading, editing and re-uploading. If you want to download a file, you can already open it and save it locally via Atom. An additional function for downloading files is therefore not considered useful.

**Comment by cschindl** [comment]
Hi @jordan-webdev,

the ability to drag and drop files for upload was already reported in issue #25 as a new feature request. I also think that this function can be helpful.
