### ISSUE TITLE
SFTP working great, can't access to FTP 

### ISSUE THREAD

**Issue by klijakub** [h3imdall/ftp-remote-edit#56]
I'm able to connect to my VPS via SFTP using ftp-workin-edit but I can't access FTP hosting. 
Loading spinner keeps rotating forever. Any ideas how to fix that?

**Comment by cschindl** [comment]
I can not reproduce the error. Please activate the debug mode and write the output here purely. The debug mode can be activated as follows:

Open the atom "config" (File -> config)
Search for "ftp-remote-edit"
Add the line as a sub-dot: "debug: true"
The config should then look something like this:

"Ftp-remote-edit":
     Config: "54baad1 ....."
     Password: "78b2 ... 622"
     Debug: true

Save and restart the Atom editor
Toogle Delevoper Tools (Ctrl + Shift + i) and open the "Console"
Then please try to connect to FTP server and post the output here.

**Comment by jkyeung** [comment]
I seem to be having this problem as well. Except that the spinners don't keep spinning. They stop, and they seem to indicate that everything is fine, but no files are found.

I tried setting the debug as you instructed OP, but nothing shows up in the console for me.

**Comment by davidtaubmann** [comment]
Hi, don't have that problem but...
That procedure shows nothing in the console, nor with minus or mayus "Debug" word
