### ISSUE TITLE
Undo just opened file

### ISSUE THREAD

**Issue by AlekseyGur** [h3imdall/ftp-remote-edit#62]
Hi!

If you open a file from remote server and press Undo (Ctrl+z) - content of the file will be deleted. Empty file will not be uploaded back to server, but anyway it is not ok. Please, could you fix it?

Best regards,
Alex.

**Comment by cschindl** [comment]
Hi @AlekseyGur,

I found the error. Changes are available in the next release.

**Comment by cschindl** [comment]
Hi @AlekseyGur,

changes are now available in current release 0.11.11. Can you please confirm the the changes fixed the reported error.
