### ISSUE TITLE
Opening hidden files. (e.g. htaccess)

### ISSUE THREAD

**Issue by LadyHD** [h3imdall/ftp-remote-edit#66]
Is it true that hidden files are not showed in the treeview from the plugin. The FTP plugin in general is great however it seems I cant seem to access my hidden files. (e.g. htaccess)

When I tried other FTP plugins for Atom they showed me the .htaccess

Am I missing something or doesn't it work. I tried following these steps hoping it would solve my problem, but too bad it did not. (http://blog.lukebennett.com/2015/09/21/show-hidden-files-in-atom-sidebar/)

Hope someone can help me out!

**Comment by cschindl** [comment]
Hi @LadyHD,

Ftp-Remote-Edit does not use the "Hide Ignored Names" and "Hide VCS Ignored Files" settings from the Atom Tree View. Changes to the settings as described in the manual therefore have no effect.

FTP-Remote-Edit displays all files which are transferred from the FTP server via the "LIST" command. However, it can happen that some misconfigured FTP server hide files. In this case, the FTP server can be forced to pass these hidden files with additional parameters. However, this does not correspond to the official FTP commands and can lead to errors.

Currently, Ftp-Remote-Edit does not support this feature. The function is therefore classified as "Feature Request" and can be integrated into a future release.
