### ISSUE TITLE
Can't open big files (>= 20 MB)

### ISSUE THREAD

**Issue by AlekseyGur** [h3imdall/ftp-remote-edit#68]
Hi.

It's impossible to open big file properly. If I open 20MB file via sftp from server, then for first few seconds it'll load normally. And it's possible to see how scroll bar become bigger. And in ~10-20 seconds Atom will crash. But It's enough free RAM (8 G) in system to open 20MB file.

Best regards,
Alex.

**Comment by cschindl** [comment]
Hi @AlekseyGur ,

changes which are made for issue "Undo just opened file #62" should also solve the problem. Now files are only displayed in the editor when they have been downloaded completely.
