### ISSUE TITLE
Status bar for upload/download

### ISSUE THREAD

**Issue by AlekseyGur** [h3imdall/ftp-remote-edit#69]
Hi.

In addition to previous issue "Can't open big files (>= 20 MB)", it would be better to make a kind of status list (queue) for operations with files. For example, in Notepad++ it looks like a list that is queue of opertaions:

![image](https://user-images.githubusercontent.com/30201077/28744535-ea6e746e-746b-11e7-97c5-e529ef41f2a1.png)

- that queue list is located below the file tree window. It shows download/upload progress of files. 

It will be very useful. Especially if you work with slow internet or big files. Sometimes it's not clear if file is already uploaded to the server or not. But with that list it'll be possible to see "stucked" files in queue.

And could you make a function "Stop the action and delete from queue" for that list? For example, if you start to open a very big file and suddenly decide not to do that or file downloading failed, you could click on row in queue window and cancel the operation.

Best regards,
Alex.

**Comment by cschindl** [comment]
Hi @AlekseyGur,

your suggestion sounds interesting. I think I will add this function in one of the next releases.
