### ISSUE TITLE
Cannot read property 'list' of null

### ISSUE THREAD

**Issue by paulo-dambros** [h3imdall/ftp-remote-edit#70]
Hi,

I am using ftp-remote-edit to control remote servers. When trying to connect to the server it does not enter and issues the following error:
"Can not read property 'list' of null"

What can it be?

PS. I'm using translate. :)

**Comment by cschindl** [comment]
Hi @paulo-dambros,
 
did you you check the credentials? The error message occurs when the (S)FTP server can not read the directory. This can happen if access rights are missing or the server terminates the connection early.

**Comment by paulo-dambros** [comment]
Hi @cschindl 
This is certainly not because credentials are used in another package. I use the same credentials in the [remote-edit](https://atom.io/packages/remote-edit) package. But the ftp-remote-edit package fits my needs very much. I even used it before formatting my machine to install a new operating system and after installing it on the new system, it presented this error. I will remove and delete all files from the atom for later reinstallation.
