### ISSUE TITLE
Git Repository Support

### ISSUE THREAD

**Issue by DDynamic** [h3imdall/ftp-remote-edit#71]
When editing files in a local git repository, atom recognizes the .git folder and reads information about the repository. It uses this information to change the colors of the files/folders to make it easier to understand the status of the repository.

It would be cool if you could implement the same functionality so when I am working on git-enabled projects on my remote servers if I could see those same colors as well, just like when editing locally.

Let me know what you think and if this could be useful. Great work so far, with this package I am able to use Atom as my main editor.

![git status](http://flight-manual.atom.io/using-atom/images/git-status.gif)

**Comment by cschindl** [comment]
Hi @DDynamic,

I think this is technically not possible because GIT only works on the local file system. Correct me if I am wrong but I know no way over FTP the GIT status of files to determine.
