### ISSUE TITLE
Grouping servers

### ISSUE THREAD

**Issue by tlygnersjo** [h3imdall/ftp-remote-edit#72]
Hi,

Thanks for a great plugin!

I would like to do a feature request. I'm working on own and customer projects and some customers have multiple projects. This leads me to the request that i want to be able to group servers in tree view.

Lets say i have Customer 1 that has Project 1, 2 and 3 and Customer 2 has Project 4 and Customer 3 has Project 5 and 6.

I want this Tree view:

**Customer 1 (group 1, not connection just a group/wrapper)**
- Project 1 (server connection)
- Project 2 (server connection)
- Project 3 (server connection)

**Customer 2 (group 2, not connection just a group/wrapper)**
- Project 4 (server connection)

**Customer 3 (group 3, not connection just a group/wrapper)**
- Project 5 (server connection)
- Project 6 (server connection)

Is this possible to implement? This kind of grouping is not always needed but if it would be available as an option i would definitely use it.

**Comment by cschindl** [comment]
Hi @tlygnersjo,

your suggestion sounds interesting. I think I will add this function in one of the next releases.

**Comment by tlygnersjo** [comment]
Oh thats great news!

Thanks a lot @cschindl, I'm glad that you liked the idea. Looking forward for an upcoming release with this feature.

Once again thanks for a awesome plugin!

**Comment by wacki4** [comment]
@cschindl - did You start something in this topic? Maybe need some help - i look forward also for this  feature.

**Comment by cschindl** [comment]
Hi @wacki4,

I'm grateful for any help. In the process of restructuring the server settings I wanted to add the grouping. Unfortunately I never got it. I had imagined that we could do the settings similar to Filezilla. But maybe you have a simpler suggestion?

**Comment by cschindl** [comment]
HI @wacki4,

I wouldn't mix the two issues. Grouping can be done relatively easily. Creating individual tabs (#54) is very complicated.

**Comment by wacki4** [comment]
So i tought about selectbox above ftp log - but about it i will write in corresponding issue.

So, any thoughts about? Making another view for groups? How do You think configuration view should look like?

**Comment by cschindl** [comment]
Hi @wacki4,

I have already prepared the configuration in the refactoring branch. I imagine it as follows:

![configuration](https://user-images.githubusercontent.com/28109094/51909929-12f82c00-23ce-11e9-9071-9cb8a6e2a381.png)


You can then select a folder for the grouping or create, edit or delete new folders by clicking on "Edit".

![folder-configuration](https://user-images.githubusercontent.com/28109094/51909989-37540880-23ce-11e9-97e1-dbad885f9334.png)

What do you think of that? Do you think you can implement it?

**Comment by wacki4** [comment]
I think it is ok - great way would be also adding folder inside folder for tree view. I think that second view could have 'parent', and sorting would be made as natural. What do You think about it?

**Comment by cschindl** [comment]
Nesting folders would be great. However, this is also the most complicated from the point of view of effort. I would therefore leave it up to you which variant you decide on.

**Comment by wacki4** [comment]
I've downloaded refactoring branch - but i don't see anything implemented for the folder settings, or field for folder in server. Did You upload it, or You only showed how it could look?

**Comment by cschindl** [comment]
The uploaded pictures should only show how to do it. These were created with Photoshop. I only added the function "editFolders" in the configuration view, which should show you how to switch from one view to the other and back. The fields, buttons, view and functions have to be implemented.

**Comment by wacki4** [comment]
Don't know where to start so, but trying ;)

**Comment by wacki4** [comment]
Did You tought where to keep folder data? As i see now You keep everything in json array for servers, not in any property there. Second file? Or same array but diffrent type of object?

**Comment by cschindl** [comment]
The configuration must be adjusted so that there is an object with the properties version (number), folder (array<Folder>) and server (array<Server>).  The server property then contains the current servers as an array.  For this a function must be created to migrate the data from the old to the new format.  The version field is for checking and future migrations. If it does not exist, the current format is converted to the new one and saved. Later then from version to version renewed adjustments can take place.

**Comment by wacki4** [comment]
@cschindl - i've created pull request #249 - please, review it if it is possible, it is my first code for electron and atom (first changes was really not so difficult as this one ;) ) - if it looks ok - i will countinue for making folders, it should now go really smooth.

**Comment by cschindl** [comment]
Changes are now included in the new release ([0.14.0](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.14.0)). 

@wacki4 Thank you very much for your great support !!!
