### ISSUE TITLE
Can't connect SFTP even enter SSH private key file

### ISSUE THREAD

**Issue by pu3antasyah** [h3imdall/ftp-remote-edit#74]
1. Download SSH Key file to my PC > then Edit Servers config of ftp-remote-edit > add key file path of file I've download to my PC >  When try to connect it will appear error  messages - Malformed private key 

2. Download Key file (ppk format) to my PC > then Edit Servers config of ftp-remote-edit > add key file path of file I've download to my PC > When try to connect it will appear error  messages - ppk mac mismatch

My PC OS: WIndows 10
Web Server: Hostgator

**Comment by cschindl** [comment]
Hi @pu3antasyah, 

the error has already been reported in issue #53. I must check that but I think the used sftp library has problems with some key file formats.
