### ISSUE TITLE
GUI broken on SSH option (Key File Field)

### ISSUE THREAD

**Issue by timothymarois** [h3imdall/ftp-remote-edit#75]
Doesn't allow you to enter your SSH key location. Field doesn't work. Can't copy and can't type.

**Comment by tbezdeka** [comment]
I've found that if I save the server settings, restart Atom and then re-edit the server, it will allow me to use that field.

**Comment by drq883** [comment]
@tbezdeka Thanks for that tip. Having to do this with each new server is simple to fix, but it is still a bug.

**Comment by cschindl** [comment]
Thanks for the tip. I will check that und hopefully find a solution.

**Comment by Svolentin** [comment]
confirm. key field read-only :(

**Comment by cschindl** [comment]
The error has been corrected 3edc534 and the changes will be available in the next release.
