### ISSUE TITLE
Cannot connect to servers after resuming from suspend (Manjaro Linux)

### ISSUE THREAD

**Issue by pjedge** [h3imdall/ftp-remote-edit#76]
If I suspend the computer while atom and ftp-remote-edit are running, then after resuming from suspend, ftp-remote-edit is unable to connect to any server and gets stuck with the spinning progress bar. Restarting atom makes it work again. I'm using Manjaro Linux (arch-based)

**Comment by cschindl** [comment]
Hi @pjedge, 

I can not reproduce the error. Please activate the debug mode and write the output here purely. The debug mode can be activated as follows:

Open the atom "config" (File -> config)
Search for "ftp-remote-edit"
Add the line as a sub-dot: "debug: true"
The config should then look something like this:

"Ftp-remote-edit":
     Config: "54baad1 ....."
     Password: "78b2 ... 622"
     Debug: true

Save and restart the Atom editor
Toogle Delevoper Tools (Ctrl + Shift + i) and open the "Console"
Then please suspend the compute, resuming and try to list directory or open remote files and if the rror occour post the output of the console here.

**Comment by matthewfeickert** [comment]
I was having this problem up through today (2017-09-22) where if I suspended my computer or even just walked to a new area of my lab and reconnected the wifi I couldn't do a write on save to the remote. I was about to open an issue, but as I was following @cschindl instructions above I noticed that [ftp-remote-edit v0.12.3](https://github.com/h3imdall/ftp-remote-edit/tree/v0.12.3) was out and I updated. Now everything works fine for me and I don't have this issue. @pjedge, is it fixed for you as well? I'm on Ubuntu.
```bash
$ uname -srvmpio
Linux 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ atom --version
Atom    : 1.19.6
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by matthewfeickert** [comment]
This issue that @pjedge described is happening again to me. In the first attachment you can see the failure to write to the remote:
![atom_upload-fail](https://user-images.githubusercontent.com/5142394/30989830-66ffd8ca-a49f-11e7-872f-d2cc3ff9619d.png)

However, after following @cschindl's instructions there didn't seem to be any actual log text to copy:
![atom_console_log](https://user-images.githubusercontent.com/5142394/30989936-cb53681e-a49f-11e7-86f7-22188a11972a.png)

Thoughts on why this might be?

**Comment by cschindl** [comment]
Hi @matthewfeickert,

first of all, thank you for your donation!

Now to your problem: The way how the debug mode was activated changed in the last releases. To activate the debug go to the package preferences and check the option "Debug Mode". After that, the console should output the logs. If the error ocour, paste it here so we can find a solution.

**Comment by matthewfeickert** [comment]
@cschindl Is there a way to export the entire console log in Developer Tools?

The following is what I have been able to copy and paste from the log which I think corresponds to the last 3 entries in the `ftp-remote-edit` logger window (screenshot below) where `example.sh` was able to be downloaded to work on but then (after changing wifi networks) `installer.sh` failed to be uploaded on two separate attempts.

Any thoughts?
```
connector:downloadFile /afs/cern.ch/user/f/feickert/testarea/test-2017-10-26/example.sh /tmp/c5467d74/lxplus.cern.ch/afs/cern.ch/user/f/feickert/testarea/test-2017-10-26/example.sh
/home/mcf/.atom/packages/ftp-remote-edit/lib/views/server-view.js:97 connector:connect
/home/mcf/.atom/packages/ftp-remote-edit/lib/views/server-view.js:97 sftp:get
/home/mcf/.atom/packages/ftp-remote-edit/lib/views/server-view.js:97 connector:disconnect
/home/mcf/.atom/packages/ftp-remote-edit/lib/views/server-view.js:94 connector:uploadFile /afs/cern.ch/user/f/feickert/testarea/test-2017-10-26/install/installer.sh /tmp/c5467d74/lxplus.cern.ch/afs/cern.ch/user/f/feickert/testarea/test-2017-10-26/install/installer.sh
/home/mcf/.atom/packages/ftp-remote-edit/lib/views/server-view.js:96 connector:createDirectory /afs/cern.ch/user/f/feickert/testarea/test-2017-10-26/install
/home/mcf/.atom/packages/ftp-remote-edit/lib/views/server-view.js:96 connector:existsDirectory /afs/cern.ch/user/f/feickert/testarea/test-2017-10-26/install
/home/mcf/.atom/packages/ftp-remote-edit/lib/views/server-view.js:97 connector:connect
/home/mcf/.atom/packages/ftp-remote-edit/lib/views/server-view.js:97 sftp:list
server-view.js [sm]:86 connector:uploadFile /afs/cern.ch/user/f/feickert/testarea/test-2017-10-26/install/installer.sh /tmp/c5467d74/lxplus.cern.ch/afs/cern.ch/user/f/feickert/testarea/test-2017-10-26/install/installer.sh
server-view.js [sm]:88 connector:createDirectory /afs/cern.ch/user/f/feickert/testarea/test-2017-10-26/install
server-view.js [sm]:88 connector:existsDirectory /afs/cern.ch/user/f/feickert/testarea/test-2017-10-26/install
server-view.js [sm]:89 connector:connect
server-view.js [sm]:89 sftp:list
```
![hanging_jobs](https://user-images.githubusercontent.com/5142394/32027311-a42d4fe4-b9e8-11e7-8842-595a857a6891.png)

**Comment by cschindl** [comment]
Hi @matthewfeickert, 

I installed a VM linux and was able to reconstruct the situation. Under linux, the sftp connection is unfortunately still considered open even after disconnection, so that all further actions fail. I wrote a small workaround 2adda6948c9dde4445143f4927f156a526d5e4d5, which hopefully solves the problem.

**Comment by matthewfeickert** [comment]
@cschindl, excellent! :+1:  Thanks for doing so, and I'll report back once I update to Rel `0.12.7`.

**Comment by matthewfeickert** [comment]
@cschindl I can confirm that now with Rel `0.12.7` I can change wifi networks in my lab and from lab to home with no problems. This is great --- thanks so much! :grinning: 

I think this issue can now be closed. Though it would be nice if @pjedge can comment on if it is working for them as well.

**Comment by cschindl** [comment]
I'm closing this now. @pjedge If the problem persists with you, I can reopen the issue.
