### ISSUE TITLE
Feature request: Option "Ignored Names"

### ISSUE THREAD

**Issue by drq883** [h3imdall/ftp-remote-edit#78]
Could you add a checkbox that will say "Don't shows .dot files or directories"?

Over the years I have so many .dot files that it takes up a bunch of space on the directory listing. It would be nice to not have them displayed.

BTW, I love this package.

**Comment by cschindl** [comment]
Hi @drq883,

I think it is not the best way to hide only .dot files. A better solution could be to implement a function like atoms "Ignored Names". So everybody could hide his preferred files.

**Comment by drq883** [comment]
Agreed. Can this request be for that option instead?
