### ISSUE TITLE
Unable to enter the master password

### ISSUE THREAD

**Issue by matthewfeickert** [h3imdall/ftp-remote-edit#79]
After installing the package through Atom when I follow the [getting started instructions](https://github.com/h3imdall/ftp-remote-edit#getting-started) the prompt for the master password is very small and partly obscured. When I then try and enter the master password and hit "Enter" nothing happens.

I know this is not much information to go off of, so please let me know if there are additional tests that I can do. This is on Ubuntu 16.04:
```bash
$ uname -srvmpio
Linux 4.4.0-91-generic #114-Ubuntu SMP Tue Aug 8 11:56:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ atom --version
Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by drq883** [comment]
I'm running the latest Atom on Mac. I'm not seeing any issue with entering the master password.

**Comment by cschindl** [comment]
Hi @matthewfeickert, 

this looks like a display error. All activated packages can load your own stylesheets. These can therefore have a negative effect on each other. Please tell us your activated packages so we can find the package that caused this error. Then we can customize our stylesheets.

**Comment by matthewfeickert** [comment]
@cschindl Following [this gist](https://gist.github.com/willgm/096f7aa8d34c83064265) my package list is (and attached: [atom-package-list.txt](https://github.com/h3imdall/ftp-remote-edit/files/1218742/atom-package-list.txt))
```
Hydrogen@1.19.0
atom-beautify@0.30.4
atom-material-syntax@1.0.6
atom-material-ui@2.0.4
build@0.68.0
build-make@0.13.0
busy@0.7.0
busy-signal@1.4.3
ex-mode@0.17.0
file-icons@2.1.10
ftp-remote-edit@0.11.11
intentions@1.1.5
language-latex@1.1.0
latextools@0.8.5
linter@2.2.0
linter-chktex@1.3.1
linter-spell@0.15.0
linter-spell-latex@0.10.0
linter-ui-default@1.6.4
merge-conflicts@1.4.5
minimap@4.29.6
python-autopep8@0.1.3
remote-edit@1.9.0
tabs-to-spaces@1.0.3
vim-mode@0.66.0
vim-mode-plus@0.96.2
vim-mode-plus-ex-mode@0.9.1
vim-mode-visual-block@0.2.16
```
Thanks for the quick feedback!

**Comment by cschindl** [comment]
Hi @matthewfeickert,

i found the mistake. The used theme "atom-material-ui" caused the display error. FTP-Remote-Edit is optimized for the supported atoms themes (Atom Light, Atom Dark, One Light, One Dark). So the theme author must change his stylesheets to support the current atom design.

If you want, you can still use your theme with this little workaround but the better way is to change the theme or create a bug issue for the theme so the author can fix it.

1. Open "File" -> "Stylesheets..."
2. Insert these lines and save them:

.overlay, atom-panel.modal {
  overflow: inherit;
}

**Comment by matthewfeickert** [comment]
@cschindl Brilliant! Thank you for the super prompt support and detailed instructions. It is truly appreciated!
