### ISSUE TITLE
Feature request: Allow for financial donations somehow

### ISSUE THREAD

**Issue by matthewfeickert** [h3imdall/ftp-remote-edit#80]
It is vitally important for me to be able to work on different clusters around the world and I would really prefer to use Atom to look at my code than just using tmux and vim for everything. This package let's me do that. As this package is literally enabling science to get done I want to be able to support it and ensure that it sticks around. Is there any way for me to make a small financial donation to the devs? I'm a graduate student, so we're just talking covering coffee fees on some days, but I'd still prefer to know that there is some support for this work.

**Comment by cschindl** [comment]
Hi @matthewfeickert,

at the moment there ist no  way to make a small financial donation. Were are happy to hear that you like our package and want support it. I will discuss that with @h3imdall, so maybe we can add an donation button for paypal or something like that.

**Comment by matthewfeickert** [comment]
I see there is [PayPal donate badge](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=KAMKHBBJH7KB2) in the README now, so I think this can get closed. :)

**Comment by matthewfeickert** [comment]
The current PayPal donate link requires the person donating to have a PayPal account. I would like to donate to support the project's development, but I don't want to open a PayPal account. Can you instead have the donate link be one that doesn't require a user account --- I am fairly certain that this is possible?

**Comment by cschindl** [comment]
Hi @matthewfeickert,

 I will discuss that with @h3imdall. Paypal was a simple way but we can also look for alternative. Do you have a suggestion?

**Comment by matthewfeickert** [comment]
@cschindl oh no, I'm not suggesting that you use something other than PayPal. I was just hoping that I could donate _through PayPal_ without having to setup a PayPal account. However, [it might be the case](https://www.paypal-community.com/t5/How-to-use-PayPal-Archive/Pay-Donate-without-Paypal-Account/td-p/41085) that to do so would require your PayPal account to be something other then the default one. If that is true then it probably isn't worth it to you to do so, and I can just setup an account --- I would just prefer to not if there isn't any downside.

**Comment by cschindl** [comment]
@matthewfeickert We misunderstood. PayPal will continue to be used. I had only asked for suggestions for other additional possibilities, such as e.g. Bitcoins or donation services. The used PayPal account supports only the possibility to donate via another PayPal account. Other donation services, however, often demand high fees, so I have to inform myself and discuss that with @h3imdall, which additional servicse are still possible for us.
