### ISSUE TITLE
Can't connect to ftp

### ISSUE THREAD

**Issue by inwardmovement** [h3imdall/ftp-remote-edit#81]
Hi,
I have 2 ftps, one connects with no problem, the second doesn't connect (loading spinner rotating forever), can you investigate please ? :)
The debug output shows only "true" in source "ftp.js:35", nothing more :s

![image](https://user-images.githubusercontent.com/9438102/29321272-2ca4b32c-81da-11e7-9521-103046e8b410.png)

**Comment by cschindl** [comment]
Hi @inwardmovement,

in "ftp.js:35" "true" is output when the server close the connection beacause of an thrown error. So please check your credentials and permissions for the ftp server.

**Comment by inwardmovement** [comment]
Usually with bad credentials I have a error notification "bad login".
I have double checked and the credentials are ok...

**Comment by cschindl** [comment]
Hi @inwardmovement, 

there may be several reasons why a server closes the connection. Maybe only one connection is allowed at the same time or the server kick you for security reasons. We had already once that the server operator blocked the IP address or did not support the complete FTP protocol. So can you please activate the debug mode und post the output? 

The debug mode can be activated as follows:

Open the atom "config" (File -> config)
Search for "ftp-remote-edit"
Add the line as a sub-dot: "debug: true"
The config should then look something like this:

"Ftp-remote-edit":
Config: "54baad1 ....."
Password: "78b2 ... 622"
Debug: true

Save and restart the Atom editor
Toogle Delevoper Tools (Ctrl + Shift + i) and open the "Console"

**Comment by inwardmovement** [comment]
I already showed the output of debug mode in the first message, isn't it right ?

**Comment by cschindl** [comment]
Are you sure that you followed the instructions and activated the debug mode? The Output should show more information then the posted.

**Comment by inwardmovement** [comment]
I managed to do it properly (I had to add a space after tabs before "debug: true").

Here is the output:
```
connector:listDirectory /www/
connector.js:58 connector:connect
ftp.js:9 ftp:connect
ftp.js:14 ftp:connect:ready
ftp.js:56 ftp:list /www/
ftp.js:20 ftp:connect:error Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at TCP.onread (net.js:572)
ftp.js:32 ftp:connect:close
ftp.js:35 true
```

**Comment by inwardmovement** [comment]
Si I found a fix [here](https://github.com/icetee/remote-ftp/issues/585)
```
- go to .atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js
- on line 106 change socket.setKeepAlive(true); -> socket.setKeepAlive(false);
- restart Atom
```
 This works ! So since Dec 2016 this fix has not been implemented yet ? Will I have to do this after each update of the plugin ?

**Comment by cschindl** [comment]
The problem therefore appears to be in the FTP library. Unfortunately, the library does not seem to be further developed. I have seen that @icetee has opened a fork (https://github.com/icetee/node-ftp) in which he has solved the problem and the library continues to maintain. In order not to make the changes to the original library after every update, I could use the fork. However, I would have to expand the server settings so that you can set the "keepalive" option manually.
