### ISSUE TITLE
A noob question...

### ISSUE THREAD

**Issue by supergabs** [h3imdall/ftp-remote-edit#87]
Hello, can i change the side of toggle? i want that in left

**Comment by drq883** [comment]
Under settings for ftp-remote-edit, there is a checkbox for "Show On Right Side".
Just uncheck that and it will show on the left side.

**Comment by supergabs** [comment]
OMG, thx <3

**Comment by AlekseyGur** [comment]
Couldn't find option "Show On Right Side" in version 0.18.0. Is it still there? "Settings / Packages / Ftp Remote Edit" ?

Found this option in code and tried to execute in console:
`atom.config.set('remote-editor.tree.showOnRightSide', true);`
But no changes :( I want it to be in right side...

**Comment by AlekseyGur** [comment]
Found that it is possible to drag-drop panel from left to right. Problem solved.
