### ISSUE TITLE
Forgotten password

### ISSUE THREAD

**Issue by kattni** [h3imdall/ftp-remote-edit#89]
Apologies for filing an issue for this. I'm running Atom on a Mac. I've forgotten the password I set. I've tried completely uninstalling the package, and removing the entire Atom preference folder from my Library. I'm still being told the password is incorrect. I'd appreciate any assistance you can provide. Thank you.

**Comment by cschindl** [comment]
Hi @kattni,

If you forgot your password, there is no way to get your server settings back. You can only reset the plugin settings and restart.

To reset the settings please follow the instructions:
1. Open config.cson "file" -> "config"
2. Delete all entries from "ftp-remote-edit:" in the config.cson
3. Save and reboot atom
4. Toggle the view with "ftp-remote-edit:toggle" or use hotkey "ctrl+space"
5. Enter a new master password

**Comment by kattni** [comment]
This is exactly what I needed. I had no intention of retrieving the settings. I understand and appreciate encryption as a feature. This package works better than any of the others and until I knew how to delete the current settings, I couldn't use it. Thank you so much for your time.

**Comment by pratapvh1** [comment]
Great.
Thank you.

**Comment by natema** [comment]
> To reset the settings please follow the instructions:
> 
>     1. Open config.cson "file" -> "config"

I just wanted to add, for those Atom newbies like me out there, that the `config.cson` file can be found by typing `Application: Open Your Config` in the Command Palette (`Ctrl+Shift+P`). It should be located in the `~/.atom` folder on Debian systems.
