### ISSUE TITLE
Permission Denied error while creating new directory

### ISSUE THREAD

**Issue by jordan-webdev** [h3imdall/ftp-remote-edit#94]
I can create files fine, but when I try to create a new directory, I get the permission denied error. How can I fix this? Is there a way I can download a log that you could see?

**Comment by cschindl** [comment]
Hi @jordan-webdev,

the only thing that you can do is to activate the debug mode. In version 0.12.0 the ftp log will be include in the view, so it will be easier to find errors in the log. Did you try the same in other ftp tools like filezilla? Maybe here you can see why you get the permission denied message.
